### ISSUE TITLE
Resolve ipython versioning

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-pinning-feedstock#1]
There was some [discussion]( https://github.com/conda-forge/staged-recipes/pull/4502#pullrequestreview-79954575 ) in the original PR at `staged-recipes` about whether `ipython` needed to have versions in the pinning file and if so how they should be limited. Adding this issue to the feedstock so that we can finish the discussion here and come to some resolution.

Current pinnings shown below:

https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/3e332e45c58c2ee3ebc3f020b833958828d07f77/recipe/conda_build_config.yaml#L70-L74

cc @msarahan @isuruf @mingwandroid

**Comment by jakirkham** [comment]
Also @minrk might be interested in this discussion and may be able to advise.

**Comment by mingwandroid** [comment]
My understanding is that this is a build matrix and not somewhere to specify pinning or version inequalities.

**Comment by isuruf** [comment]
> My understanding is that this is a build matrix and not somewhere to specify pinning or version inequalities.

It's both. Build matrix for and pinning.

We haven't needed any ipython pinning yet, so my preference is to skip this.

**Comment by msarahan** [comment]
The text is arbitrary, so it could be used to put in version inequalities.  Doing so would break things like pin_compatible, and I wouldn't advise it generally.

A build matrix with one element is "pinned" I would say.  If you care about versions in any way, you express that in conda_build_config.yaml

**Comment by minrk** [comment]
I'm not aware of things that need to pin IPython version (maybe other things, like `notebook` or other formerly-IPython packages, but not IPython itself).

**Comment by isuruf** [comment]
Fixed in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3
