### ISSUE TITLE
cxx_compiler_version incompatible with nvcc

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-forge-pinning-feedstock#1000]
On the faiss-feedstock, we're building per cuda-version, and with the recent compiler upgrades, this now hits the limit for what nvcc supports: 
```
/usr/local/cuda/bin/nvcc -I /usr/local/cuda/targets/x86_64-linux/include/ -Xcompiler -fPIC -Xcudafe --diag_suppress=unrecognized_attribute -gencode=arch=compute_35,code=sm_35 -gencode=arch=compute_50,code=sm_50 -gencode=arch=compute_52,code=sm_52 -gencode=arch=compute_60,code=sm_60 -gencode=arch=compute_61,code=sm_61 -gencode=arch=compute_70,code=sm_70 -gencode=arch=compute_75,code=sm_75 -gencode=arch=compute_75,code=compute_75 -lineinfo -ccbin /home/conda/feedstock_root/build_artifacts/faiss-split_1606947926843/_build_env/bin/x86_64-conda-linux-gnu-c++ -std=c++14 -DFAISS_USE_FLOAT16 -I. -g -O3 -c gpu/GpuDistance.cu -o gpu/GpuDistance.o
In file included from /usr/local/cuda/targets/x86_64-linux/include/cuda_runtime.h:83,
                 from <command-line>:
/usr/local/cuda/targets/x86_64-linux/include/crt/host_config.h:138:2: error: #error -- unsupported GNU version! gcc versions later than 8 are not supported!
  138 | #error -- unsupported GNU version! gcc versions later than 8 are not supported!
      |  ^~~~~
```

I've been trying what feels like dozens of different ways (e.g. [here](https://github.com/conda-forge/faiss-split-feedstock/pull/18#issuecomment-737564530)) to work around this using a local `conda_build_config.yaml`, but it seems the pinning always overrides my values in `_combine_spec_dictionaries` and then I get zipkey-length-conflicts.

Rather than trying to figure out how to fix this on a per-feedstock basis, I'm  I'm now thinking that this should be fixed on the cfp-side directly (hence this issue), because presumably other recipes will also (eventually) be affected.

**Comment by mbargull** [comment]
From https://github.com/conda-forge/faiss-split-feedstock/pull/18#issuecomment-737564530 :
> ```
> ValueError: All entries associated by a zip_key field must be the same length.
> [...]
> cxx_compiler_version and cuda_compiler_version are different (1 and 5)
> ```
Smells like https://github.com/conda/conda-build/issues/3974 ...

**Comment by jakirkham** [comment]
Also likely related to issue ( https://github.com/conda-forge/nvcc-feedstock/issues/51 ).

**Comment by leofang** [comment]
@isuruf Does it make sense to change this part of the migrator
https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/76faade6a0376542928c84b2c236a22e3b0a8f98/recipe/migrations/cuda110.yaml#L29-L34
as follows?
```
 c_compiler_version:     # [linux] 
   - 7                   # [linux64 or aarch64] 
   - 8                   # [ppc64le] 
   - 9                   # [cuda_compiler_version == '11.0']
 cxx_compiler_version:   # [linux] 
   - 7                   # [linux64 or aarch64] 
   - 8                   # [ppc64le] 
   - 9                   # [cuda_compiler_version == '11.0']
```
This way when using CUDA 11.0 we can use gcc 9, which is recommend in the Installation Guide, but for older CUDA we use gcc 7.

**Comment by isuruf** [comment]
No, only selectors allowed are the os/arch selectors.

**Comment by leofang** [comment]
I see. So is there a way to enable gcc 9 for CUDA 11+?

**Comment by leofang** [comment]
> I see. So is there a way to enable gcc 9 for CUDA 11+?

btw for context: with https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1052 all CUDA builds fall back to gcc 7 now, so it works for all CUDA versions (9.2 - 11.0). The discussion is about enabling gcc 9 for CUDA 11.0+ only.

**Comment by h-vetinari** [comment]
> I see. So is there a way to enable gcc 9 for CUDA 11+?

I can't speak about the migrator, and how it's affected by updates to zip-keys in the pinning, but generally, it should be possible to add `c[xx]_compiler_version` to the `zip_keys` involving the `cuda_compiler_version` to get that.

**Comment by h-vetinari** [comment]
Closing this out as out-of-date (was solved in the meantime by https://github.com/conda-forge/conda-smithy/pull/1544 and follow-ups).
