### ISSUE TITLE
Relax glib pinning

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/conda-forge-pinning-feedstock#1026]
Would we be able to relax the glib pinning.

When trying to move qt forward, the glib 2.64.6 migration is causing libffi to be pinned to 3.2, but many packages have already moved forward to libffi 3.3

glib seems to be pretty stable these days, maybe we can pin to `2` instead of `2.x.x` 
https://abi-laboratory.pro/index.php?view=timeline&l=glib

It seems that even the glib package doesn't pin so hard.

Is there a way i can relax a migration that is already in place?

**Comment by isuruf** [comment]
Issue is that newer glib versions have a higher macos requirement. We can make the bot know that the 2.64 branch needs migrations too.

**Comment by isuruf** [comment]
nvm, newer glib versions fixed this issue. Maybe we can remove https://github.com/conda-forge/glib-feedstock/blob/master/recipe/conda_build_config.yaml#L1-L2 and try again

**Comment by hmaarrfk** [comment]
thanks for the detailed explanation. There still seems to be one issue with the qt migration that I can't put my finger on :(

**Comment by hmaarrfk** [comment]
so, now how do we close out this migration? Can i edit the original migration file?

**Comment by isuruf** [comment]
the migration was not for a version update. it was to replace `glib` run requirement (which pulls in python) with `libglib` requirement. We can change the migrator to use `2.66`. I don't know why the migrator was called `glib2646` which is a misnomer. cc @xhochy

**Comment by xhochy** [comment]
+1 to change the migrator to `2.66` and the global pin to 2. No need for a new migration.
