### ISSUE TITLE
Minimum pinned versions for numpy

### ISSUE THREAD

**Issue by dpryan79** [conda-forge/conda-forge-pinning-feedstock#118]
Issue: For python modules that use numpy's C API, the dependency bounds defined by `pin_compatible('numpy')` are invalid.

<br/>
Environment (<code>conda list</code>): See https://github.com/bioconda/bioconda-recipes/issues/10671 for a real world example

In short, I wonder about the goal of setting a minimum version of numpy that is quite old (https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml#L426-L428 ). If the goal is to allow pure python packages that use numpy to have a convenient method to set the numpy version range then this should work fine. However, this does not work for python modules that use the numpy C API. This is due to that API being versioned (c.f., https://github.com/numpy/numpy/blob/464f79eb1d05bf938d16b49da1c39a4e02506fa3/numpy/core/setup_common.py#L35-L44 ). Currently, any package using the numpy C API and `pin_compatible('numpy')` will not actually be compatible with the numpy version range produced (`numpy >=1.9.3,<2.0a0` and see the aforementioned bioconda issue for a real-world example).

So if it's recommended that `pin_compatible('numpy')` be used by packages using the numpy C API, then I would suggest that the minimum version be bumped to 1.14 and that whoever takes on the responsibility of bumping the numpy version used by conda-forge takes care that this is bumped in a coordinated manner. One might also set a maximum version, since it's likely that a future 1.* version of numpy will once again change its API.

If it's not recommended that `pin_compatible('numpy')` be used by packages using the numpy C API, then that's fine and projects like bioconda will want to mention that in the documentation. This would be unfortunate, since it makes coordinated package upgrades difficult, but so it goes.

Xref: https://github.com/bioconda/bioconda-recipes/issues/10671
Xref: https://github.com/bioconda/bioconda-recipes/pull/10876

**Comment by isuruf** [comment]
Please read the docs on the correct pinning here, https://conda-forge.org/docs/meta.html#building-against-numpy

You had,
```
host:
  - {{ pin_compatible('numpy') }}
run:
  - {{ pin_compatible('numpy') }}
```
It should have been
```
host:
  - numpy
run:
  - {{ pin_compatible('numpy') }}
```

**Comment by dpryan79** [comment]
Sure enough that works, not sure how I missed that in the documentation, thanks!

**Comment by ocefpaf** [comment]
> Sure enough that works, not sure how I missed that in the documentation, thanks!

Our docs are not the most user friendly thing out there :grimacing: 

If you have any suggestions on how to make them better please send a PR :wink:
