### ISSUE TITLE
Update glib to 2.56?

### ISSUE THREAD

**Issue by pkgw** [conda-forge/conda-forge-pinning-feedstock#119]
Defaults has updated to glib 2.56, while we're still pinning to 2.55. Does this mean that we should consider updating our pin?

Motivated by [pygobject-feedstock #9](https://github.com/conda-forge/pygobject-feedstock/issues/9).

**Comment by ocefpaf** [comment]
:+1: 

Do you want to send the PR?

**Comment by pkgw** [comment]
Can do, but we should probably build 2.56 first ... Also, I have a patch to start building glib on Windows. With the gettext PR merged I believe that should be ready to go; I'll submit unless it turns out that I've forgotten something.

**Comment by ocefpaf** [comment]
> Can do, but we should probably build 2.56 first 

I tried is some time ago and forgot I never sent the PR.

Do you want to do that so you can add you patch?

**Comment by pkgw** [comment]
[glib-feedstock #35](https://github.com/conda-forge/glib-feedstock/pull/35). I'll try bumping to 2.56 and see if it works.

**Comment by pkgw** [comment]
Done.
