### ISSUE TITLE
Question: how to update tbb to incompatible version safely?

### ISSUE THREAD

**Issue by AlexVeprev** [conda-forge/conda-forge-pinning-feedstock#1227]
Hi,

Could you please clarify if something should be added into [recipe/conda_build_config.yam](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml) in order to merge https://github.com/conda-forge/tbb-feedstock/pull/78?
Should I care about it as tbb-feedstock maintainer or can just merge my PR?

I've already asked such question in https://github.com/conda-forge/tbb-feedstock/issues/75, got an answer that this case is resolvable, but I still don't understand if I should do something on my side before merge.

Thanks in advance!

**Comment by chrisburr** [comment]
I haven't read the issues fully but I think there needs to be a patch added here before you merge that PR to avoid breaking all installations that use binaries build with the old `tbb`: https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/tree/master/recipe

This need edit  `gen_patch_json.py` as summarised in https://github.com/conda-forge/tbb-feedstock/issues/75#issuecomment-738246009. You can check how the repodata is being changed by running `show_diff.py`.

Would you be able to try and make a PR? If you need more guidance for writing the patch let me know.

**Comment by AlexVeprev** [comment]
@chrisburr, thank you for pointing exactly to `gen_patch_json.py`, I think I've got the idea: I should add something like `<2021` to `tbb` line in `depends` of each package depeding on TBB in repodata using `gen_patch_json.py`, I will try to do it, but I still have a questions: should I apply any PR to this repo (conda-forge-pinning-feedstock) or just to repodata-patches?

**Comment by isuruf** [comment]
Here's the order of things to do.
1. Rebuild the old 2020 package with correct run_exports (i.e. add an upper bound of 2020)
2. Send a PR to `conda-forge-repodata-patches`
3. Send a PR to `conda-forge-pinning` for a migrator so that all downstream packages are rebuilt with 2021.

**Comment by AlexVeprev** [comment]
@isuruf, thank you!

1. PR https://github.com/conda-forge/tbb-feedstock/pull/79
2. PR https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/124
3. Not started yet...

I'm not quite confident in right understanding of required changes in the PRs above, so I'll really appreciate any feedback.

**Comment by isuruf** [comment]
Thanks. I also added 1b which I forgot earlier.

**Comment by AlexVeprev** [comment]
@isuruf, I'd appreciate some help regarding
>  3. Send a PR to conda-forge-pinning for a migrator so that all downstream packages are rebuilt with 2021.

Have you really meant 2021? Or 2020? 
I've read through [Making Migrators](https://regro.github.io/cf-scripts/migrators.html) and [CFEP-9](https://github.com/conda-forge/cfep/blob/master/cfep-09.md).

Should I put smth like this to recipe/migrations/tbb2020.yaml?
```yaml
migrator_ts: <timestamp>
__migrator:
  kind: version
  build_number: 1
  migration_number: 1
tbb:
- 2020
```

Should I take care of tbb-devel migration here?

And one more question: does migrator PR block merge of https://github.com/conda-forge/tbb-feedstock/pull/78? Or more generally: does anything block https://github.com/conda-forge/tbb-feedstock/pull/78 from safe (from dependent packages perspective) merge?

**Comment by chrisburr** [comment]
> Have you really meant 2021? Or 2020?

Yes, it should be to rebuild with 2021. The idea being to rebuild all packages so the "default" becomes 2021 and we can then forget about 2020 once the migration is finished.

I think https://github.com/conda-forge/tbb-feedstock/pull/78 can now be merged but you should give someone who it more knowledgable about the pinnings a chance to tell me I'm forgetting something 😄

**Comment by AlexVeprev** [comment]
Thanks, @chrisburr! Sorry, maybe my questions are too naïve but I still have some 😄 

How should the migrator look like?
 recipe/migrations/tbb2021.yaml
```yaml
migrator_ts: <timestamp>
__migrator:
  kind: version
  build_number: 1
  migration_number: 1
tbb:
- 2021
```
Something like that?

Now I understand that the migrator should be merged **_after_** deployment of oneTBB 2021, right?

**Comment by isuruf** [comment]
> Something like that?

Yes, but add `tbb_devel: - 2021` as well.

> Now I understand that the migrator should be merged after deployment of oneTBB 2021, right?

Yes

**Comment by AlexVeprev** [comment]
PR for "3" is here: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1293.
There is another automatic PR https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1291, but it doesn't contain tbb-devel.

**Comment by AlexVeprev** [comment]
Hi @isuruf, @chrisburr, PR for "3" (#1293) is still open, but I've addressed a comment. Should I do something else in scope of oneTBB 2021.1.1 enabling? If no I'll close the issue.

I really appreciate your help in scope of this long migration, thank you very much!
