### ISSUE TITLE
Bump glpk to 4.65

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-pinning-feedstock#13]
ref: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/7#pullrequestreview-98457907

cc @dougalsutherland

**Comment by dougalsutherland** [comment]
Needs to wait on https://github.com/conda-forge/glpk-feedstock/pull/27, though. :)

**Comment by jakirkham** [comment]
Addressing in PR ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/21 ).
