### ISSUE TITLE
gcc7 label?

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-pinning-feedstock#132]
There is a `gcc7` label for one of the `conda-forge-pinning` packages. Is this significant somehow?

<img width="1552" alt="screen shot 2018-10-11 at 16 37 47" src="https://user-images.githubusercontent.com/3019665/46832439-047cfa80-cd74-11e8-8d39-e8bbcd379fb3.png">

**Comment by mariusvniekerk** [comment]
Think i made that at some point to test out a staged-recipes idea.
