### ISSUE TITLE
pin libwebp to 1.0.0 or migrate 0.5 to new compilers

### ISSUE THREAD

**Issue by croth1** [conda-forge/conda-forge-pinning-feedstock#134]
Only version 1.0 of libwebp is migrated to the new compilers, but it is pinned to 0.5. This leads to problems like here: https://github.com/conda-forge/libgd-feedstock/pull/25. It looks like we either have to move the pin or migrate libwebp 0.5 as well.

Any preferences?

**Comment by croth1** [comment]
ping @conda-forge/core

**Comment by ocefpaf** [comment]
> Any preferences?

I would say just update the pin. It is easier and move the stack "forward."

**Comment by croth1** [comment]
oh it seems like this is already done in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/137.

**Comment by ocefpaf** [comment]
> oh it seems like this is already done in #137.

Well, I've been running/cleaning after the bot for so long that I forgot I sent that PR :rofl: 

Sorry about that. Closing this then.
