### ISSUE TITLE
Is opencl supported on all CPUs???

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/conda-forge-pinning-feedstock#1379]
I would like to compile a package with opencl support.

However, i don't understand if this will cause the package to be incompatible with certain computers.

What happens when a system is programmed with opencl and the processor doesn't support it? Does opencl fallback to a software only implementation?

This is the package in question:
https://github.com/conda-forge/enblend-feedstock/pull/6

**Comment by isuruf** [comment]
`ocl-icd` and `khronos-opencl-icd-loader` are two loaders. They are not implementations and does not run by themselves. You need OpenCL implementations. For macOS, if you add `ocl_icd_wrapper_apple` to `run` requirements, then you'll be able to use the OpenCL implementation from Apple. For Linux, if you add `ocl-icd-system` to `run` requirements, you'll be able to use the OpenCL implementation in your system (possibly from NVIDIA).
There are also some OpenCL implementations packaged as conda packages. `pocl` supports all CPUs supported by LLVM on Linux and macOS.

**Comment by hmaarrfk** [comment]
thanks for the detailed information. What about windows?

**Comment by isuruf** [comment]
pocl doesn't support windows atm. You can install Intel's OpenCL implementation. (We are in the process of making a conda package for it)

**Comment by hmaarrfk** [comment]
Ok. Got it. So for now. It seems that intel open l is not packaged yet and as such likely best to avoid opencl on windows.
