### ISSUE TITLE
Support for coremltools on Mac M1 Silicon Needed -- PR Request

### ISSUE THREAD

**Issue by GR899** [conda-forge/conda-forge-pinning-feedstock#1414]
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Direct support needed for coremltools WITHOUT the need to reinstall or rebuild numpy or scipy. Or the need to rebuild opencv, which again is working correctly with no need to rebuild.

All suggestions on installing fail using suggestions outlined here:

https://github.com/apple/coremltools/issues/1156

AGAIN -- Everything I need for my work is currently and correctly loaded into my working environment with the exception of coremltools.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
# Name                    Version                   Build  Channel
absl-py                   0.12.0             pyhd8ed1ab_0    conda-forge
aiohttp                   3.7.4            py38h30f7421_0    conda-forge
anyio                     2.2.0            py38h10201cd_0    conda-forge
appnope                   0.1.2            py38h10201cd_1    conda-forge
argon2-cffi               20.1.0           py38h30f7421_2    conda-forge
astor                     0.8.1              pyh9f0ad1d_0    conda-forge
astunparse                1.6.3              pyhd8ed1ab_0    conda-forge
async-timeout             3.0.1                   py_1000    conda-forge
async_generator           1.10                       py_0    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
babel                     2.9.0              pyhd3deb0d_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.3              pyhd8ed1ab_0    conda-forge
bleach                    3.3.0              pyh44b312d_0    conda-forge
blinker                   1.4                        py_1    conda-forge
brotlipy                  0.7.0           py38h30f7421_1001    conda-forge
bzip2                     1.0.8                h27ca646_4    conda-forge
c-ares                    1.17.1               h27ca646_1    conda-forge
ca-certificates           2020.12.5            h4653dfc_0    conda-forge
cached-property           1.5.2                hd8ed1ab_1    conda-forge
cached_property           1.5.2              pyha770c72_1    conda-forge
cachetools                4.2.1              pyhd8ed1ab_0    conda-forge
cairo                     1.16.0            he69dfd1_1008    conda-forge
certifi                   2020.12.5        py38h10201cd_1    conda-forge
cffi                      1.14.5           py38he62ddd7_0    conda-forge
chardet                   4.0.0            py38h10201cd_1    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cryptography              3.4.7            py38h3c0dae5_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cython                    0.29.22                  pypi_0    pypi
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
entrypoints               0.3             pyhd8ed1ab_1003    conda-forge
ffmpeg                    4.3.1                h22aafd7_2    conda-forge
fontconfig                2.13.1            h751047c_1004    conda-forge
freetype                  2.10.4               h17b34a0_1    conda-forge
future                    0.18.2           py38h10201cd_3    conda-forge
gast                      0.4.0              pyh9f0ad1d_0    conda-forge
gettext                   0.19.8.1          hea66d9f_1005    conda-forge
gmp                       6.2.1                h9f76cd9_0    conda-forge
gnutls                    3.6.13               h706517b_1    conda-forge
google-auth               1.28.0             pyh44b312d_0    conda-forge
google-auth-oauthlib      0.4.1                      py_2    conda-forge
google-pasta              0.2.0              pyh8c360ce_0    conda-forge
graphite2                 1.3.13            h9f76cd9_1001    conda-forge
grpcio                    1.36.1           py38h446835f_0    conda-forge
h5py                      3.1.0           nompi_py38h032b01a_100    conda-forge
harfbuzz                  2.8.0                h2a75196_1    conda-forge
hdf5                      1.10.6          nompi_h0fc092c_1114    conda-forge
icu                       68.1                 h17758a7_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
importlib-metadata        3.10.0           py38h10201cd_0    conda-forge
ipykernel                 5.5.3            py38h2cb4d76_0    conda-forge
ipython                   7.22.0           py38h2cb4d76_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jasper                    2.0.14               h9af5a26_2    conda-forge
jedi                      0.18.0           py38h10201cd_2    conda-forge
jinja2                    2.11.3             pyh44b312d_0    conda-forge
joblib                    1.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h27ca646_0    conda-forge
json5                     0.9.5              pyh9f0ad1d_0    conda-forge
jsonschema                3.2.0              pyhd8ed1ab_3    conda-forge
jupyter-packaging         0.7.12             pyhd8ed1ab_0    conda-forge
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_core              4.7.1            py38h10201cd_0    conda-forge
jupyter_server            1.5.1            py38h10201cd_0    conda-forge
jupyterlab                3.0.12             pyhd8ed1ab_0    conda-forge
jupyterlab_pygments       0.1.2              pyh9f0ad1d_0    conda-forge
jupyterlab_server         2.4.0              pyhd8ed1ab_0    conda-forge
keras                     2.4.3                    pypi_0    pypi
keras-preprocessing       1.1.2              pyhd8ed1ab_0    conda-forge
kiwisolver                1.3.1            py38h12a6f45_1    conda-forge
krb5                      1.17.2               h17618d6_0    conda-forge
lame                      3.100             h27ca646_1001    conda-forge
lcms2                     2.12                 had6a04f_0    conda-forge
libblas                   3.9.0                8_openblas    conda-forge
libcblas                  3.9.0                8_openblas    conda-forge
libcurl                   7.75.0               h222edf9_0    conda-forge
libcxx                    11.1.0               h168391b_0    conda-forge
libedit                   3.1.20191231         hc8eb9b7_2    conda-forge
libev                     4.33                 h642e427_1    conda-forge
libffi                    3.3                  h9f76cd9_2    conda-forge
libgfortran               5.0.0.dev0      11_0_1_hf114ba7_21    conda-forge
libgfortran5              11.0.1.dev0         hf114ba7_21    conda-forge
libglib                   2.68.0               haaa185a_2    conda-forge
libiconv                  1.16                 h642e427_0    conda-forge
liblapack                 3.9.0                8_openblas    conda-forge
liblapacke                3.9.0                8_openblas    conda-forge
libnghttp2                1.43.0               hf3018f0_0    conda-forge
libopenblas               0.3.12          openmp_h2ecc587_1    conda-forge
libopencv                 4.5.1            py38hb421fe0_1    conda-forge
libpng                    1.6.37               hf7e6567_2    conda-forge
libprotobuf               3.15.6               habe5f53_0    conda-forge
libsodium                 1.0.18               h27ca646_1    conda-forge
libssh2                   1.9.0                hb80f160_6    conda-forge
libtiff                   4.2.0                h70663a0_0    conda-forge
libwebp-base              1.2.0                h27ca646_2    conda-forge
libxml2                   2.9.10               h8f9ca65_3    conda-forge
llvm-openmp               11.1.0               hb3022d6_0    conda-forge
lz4-c                     1.9.3                h9f76cd9_0    conda-forge
markdown                  3.3.4              pyhd8ed1ab_0    conda-forge
markupsafe                1.1.1            py38h30f7421_3    conda-forge
matplotlib                3.4.1            py38h150bfb4_0    conda-forge
matplotlib-base           3.4.1            py38hb140015_0    conda-forge
mistune                   0.8.4           py38h30f7421_1003    conda-forge
multidict                 5.1.0            py38h30f7421_1    conda-forge
nbclassic                 0.2.6              pyhd8ed1ab_0    conda-forge
nbclient                  0.5.3              pyhd8ed1ab_0    conda-forge
nbconvert                 6.0.7            py38h10201cd_3    conda-forge
nbformat                  5.1.2              pyhd8ed1ab_1    conda-forge
ncurses                   6.2                  h9aa5885_4    conda-forge
nest-asyncio              1.5.1              pyhd8ed1ab_0    conda-forge
nettle                    3.6                  hc6a1b29_0    conda-forge
ninja                     1.10.2               h4d860bb_0    conda-forge
notebook                  6.3.0            py38h10201cd_0    conda-forge
numpy                     1.20.2           py38hbf7bb01_0    conda-forge
oauthlib                  3.0.1                      py_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
onnx                      1.8.1                    pypi_0    pypi
opencv                    4.5.1            py38h150bfb4_1    conda-forge
openh264                  2.1.1                habe5f53_0    conda-forge
openssl                   1.1.1k               h27ca646_0    conda-forge
opt_einsum                3.3.0                      py_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pandas                    1.2.3            py38h9b9bf68_0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.8.1              pyhd8ed1ab_0    conda-forge
pcre                      8.44                 hb904e53_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.1.2            py38h5cebd47_0    conda-forge
pip                       20.2.4                     py_0    conda-forge
pixman                    0.40.0               h27ca646_0    conda-forge
prometheus_client         0.9.0              pyhd3deb0d_0    conda-forge
prompt-toolkit            3.0.18             pyha770c72_0    conda-forge
protobuf                  3.15.6           py38h3f7e68f_0    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py-opencv                 4.5.1            py38hab544c7_1    conda-forge
pyasn1                    0.4.8                      py_0    conda-forge
pyasn1-modules            0.2.7                      py_0    conda-forge
pycocotools               2.0.2                    pypi_0    pypi
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.8.1              pyhd8ed1ab_0    conda-forge
pyjwt                     2.0.1              pyhd8ed1ab_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyrsistent                0.17.3           py38h30f7421_2    conda-forge
pysocks                   1.7.1            py38h10201cd_3    conda-forge
python                    3.8.8           h12cc5a1_0_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-flatbuffers        1.12               pyhd8ed1ab_0    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytorch                   1.8.0           cpu_py38hc43b888_0    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pyyaml                    5.4.1                    pypi_0    pypi
pyzmq                     22.0.3           py38h876209b_1    conda-forge
readline                  8.1                  hfbdcbf2_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
requests-oauthlib         1.3.0              pyh9f0ad1d_0    conda-forge
rsa                       4.7.2              pyh44b312d_0    conda-forge
scikit-learn              0.24.1           py38h397cc00_0    conda-forge
scipy                     1.6.2            py38hd0c9ec0_0    conda-forge
seaborn                   0.11.1                   pypi_0    pypi
send2trash                1.5.0                      py_0    conda-forge
setuptools                49.6.0           py38h10201cd_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sleef                     3.5.1                h27ca646_1    conda-forge
sniffio                   1.2.0            py38h10201cd_1    conda-forge
sqlite                    3.35.3               h6d56c25_0    conda-forge
tensorboard               2.4.1              pyhd8ed1ab_0    conda-forge
tensorboard-plugin-wit    1.8.0              pyh44b312d_0    conda-forge
tensorflow                2.4.0rc0                 pypi_0    pypi
tensorflow-addons         0.11.2                   pypi_0    pypi
tensorflow-estimator      2.4.0              pyh9656e83_0    conda-forge
termcolor                 1.1.0                      py_2    conda-forge
terminado                 0.9.4            py38h10201cd_0    conda-forge
testpath                  0.4.4                      py_0    conda-forge
thop                      0.0.31-2005241907          pypi_0    pypi
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
tk                        8.6.10               hf7e6567_1    conda-forge
torchvision               0.2.2.post3              pypi_0    pypi
tornado                   6.1              py38h30f7421_1    conda-forge
tqdm                      4.59.0                   pypi_0    pypi
traitlets                 5.0.5                      py_0    conda-forge
typeguard                 2.11.1             pyhd8ed1ab_0    conda-forge
typing-extensions         3.7.4.3                       0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
urllib3                   1.26.4             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
webencodings              0.5.1                      py_1    conda-forge
werkzeug                  1.0.1              pyh9f0ad1d_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
wrapt                     1.12.1           py38h30f7421_3    conda-forge
x264                      1!161.3030           h27ca646_0    conda-forge
xz                        5.2.5                h642e427_1    conda-forge
yarl                      1.6.3            py38h30f7421_1    conda-forge
zeromq                    4.3.4                h9f76cd9_0    conda-forge
zipp                      3.4.1              pyhd8ed1ab_0    conda-forge
zlib                      1.2.11            h31e879b_1009    conda-forge
zstd                      1.4.9                h5b28eab_0    conda-forge

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
active environment : apple_tensorflow
    active env location : /Users/XX/miniforge3/envs/apple_tensorflow
            shell level : 1
       user config file : /Users/XX/.condarc
 populated config files : /Users/XX/miniforge3/.condarc
          conda version : 4.10.0
    conda-build version : not installed
         python version : 3.8.6.final.0
       virtual packages : __osx=11.2.2=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/XX/miniforge3  (writable)
      conda av data dir : /Users/XX/miniforge3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/XX/miniforge3/pkgs
                          /Users/XX/.conda/pkgs
       envs directories : /Users/XX/miniforge3/envs
                          /Users/XX/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.10.0 requests/2.25.1 CPython/3.8.6 Darwin/20.3.0 OSX/11.2.2
                UID:GID : 501:20
             netrc file : None
           offline mode : False

**Comment by isuruf** [comment]
@GR899, can you send a PR to add `coremltools` to the list at https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/osx_arm64.txt ?

**Comment by GR899** [comment]
@isuruf No I can't -- I can create an issue not a PR -- can you please create one for me? This is completely stopping progress on a huge project. Thanks.

**Comment by isuruf** [comment]
> No I can't

Why not?

**Comment by GR899** [comment]
Because I haven't forked a branch it won't let me and ALL I WANT IS THIS ISSUE FIXED. I've spent two hours trying to figure out how to make the pull request and at every turn it won't let me. SO, can you please just submit the request on my behalf. Again, this is stopping a huge project -- thanks for your help.

**Comment by k-dominik** [comment]
> Because I haven't forked a branch it won't let me and ALL I WANT IS THIS ISSUE FIXED. I've spent two hours trying to figure out how to make the pull request and at every turn it won't let me. SO, can you please just submit the request on my behalf. Again, this is stopping a huge project -- thanks for your help.

Hm, you can edit/fork/open a PR all in one go if you [navigate to the file](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/migrations/osx_arm64.txt) and click on the little pencil icon:

![edit](https://user-images.githubusercontent.com/24434157/114195332-a9cab680-9950-11eb-950c-f106a8f56890.png)

Cheers

**Comment by GR899** [comment]
Thank you -- I believe I was able to make the request. Thanks for your assistance and apologies for any errors that I made in advance.

**Comment by k-dominik** [comment]
cool! I think now you only have to open a pull request here: https://github.com/conda-forge/conda-forge-pinning-feedstock/pulls

(here are the github docs for pull requests, for reference: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request)

**Comment by GR899** [comment]
I did that see above.

**Comment by k-dominik** [comment]
I think above you have created a commit on your own fork of the conda-forge-pinning-feedstock: https://github.com/GR899/conda-forge-pinning-feedstock/tree/patch-1

I think if you click there, it should even offer you do open a pull request with the upstream repository. Once you have succeeded, you should be able to see it here: https://github.com/conda-forge/conda-forge-pinning-feedstock/pulls?q=is%3Aopen+is%3Apr+

**Comment by GR899** [comment]
@k-dominik many thanks - I hope it is now complete. Appreciate your insights and kind suggestions.

**Comment by jakirkham** [comment]
The PR was merged. Closing this out

**Comment by GR899** [comment]
@jakirkham THIS IS NOT FIXED -- just tried to install using pip under conda 4.10.0 and *still* receive the numpy error: could not build wheels for numpy which use PEP 517 and cannot be installed directly.

**Comment by jakirkham** [comment]
All this repo does is generate migration PRs, which it has done. There's likely work that will still need to be done at the feedstock level. If this is something of interest to you, would suggest taking a look at the PR and see what is needed to get it fixed up and integrated. It appears this is PR ( https://github.com/conda-forge/coremltools-feedstock/pull/15 )
