### ISSUE TITLE
3.6 pypy builds removed in rerender before 3.7 pypy migration complete

### ISSUE THREAD

**Issue by tkelman** [conda-forge/conda-forge-pinning-feedstock#1463]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue: Can't tell if this was intentional or not, but something between 2021.04.27.07.37.24 (https://github.com/conda-forge/awscli-feedstock/commit/392e575c901120e7c27af0792e324c6a46f9eacb) and 2021.05.03.19.31.03 (https://github.com/conda-forge/awscli-feedstock/pull/797/commits/665d3a756ecbe4423fabafd3c32e38a5d5ca12bd) dropped the CI builds for python 3.6 pypy. That feedstock has an open PR for 3.7 pypy migration, but it's been blocked by dependency upper bounds and a different feedstock.

<br/>
Environment: Travis, Drone, Github Actions CI

**Comment by isuruf** [comment]
Thanks for the report. Please rerender in another 10 minutes and report back.

**Comment by tkelman** [comment]
Looks great, thanks for the quick fix!
https://github.com/conda-forge/awscli-feedstock/pull/797/commits/db0719cc736f8ec49f7935d138f49ca3a97437cd
