### ISSUE TITLE
NOT FIXED Support for coremltools on Mac M1 Silicon Needed -- PR Request #1414

### ISSUE THREAD

**Issue by GR899** [conda-forge/conda-forge-pinning-feedstock#1470]
This is NOT fixed -- tried after @jakirkham reported issue is closed and I can report that running conda 4.10.0 and under all the same circumstances previously reported, doing a pip install coremltools results in the SAME **Error: Could not build wheels for numpy which use PEP 517 and cannot be installed directly.** 

PLEASE STOP trying to install numpy which in my environment is correctly installed. I have numpy 1.20.2 correctly installed -- coremltools DOES NOT NEED TO REBUILD IT

Please fix this or ADVISE how to get this to install.

**Comment by isuruf** [comment]
You can help over at  conda-forge/coremltools-feedstock#15

Please reduce your usage of all caps words in the future.
