### ISSUE TITLE
Remove `cudnn` from the global CUDA zipping?

### ISSUE THREAD

**Issue by leofang** [conda-forge/conda-forge-pinning-feedstock#1554]
See the discussion starting https://github.com/conda-forge/cudnn-feedstock/issues/18#issuecomment-825759446. Currently we zip `cudnn` with `docker_image`, `cuda_compiler_version`, and `cdt_name`:
https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/4443017f08b34320110b6046e312527027ba5a26/recipe/conda_build_config.yaml#L141-L145
I know it was done in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1051, but in retrospect it probably could have been handled differently. This zipping treats cuDNN differently from all other CUDA packages like cuTENSOR, cuSPARSELt, NCCL, etc, but it is not necessary and is error prone. I think making it depend on the CUDA version via `run_exports` is probably a better solution.

@conda-forge/core I am thinking a 3-step plan involving a "de-migrator":
1. Rebuilding cuDNN to use `run_exports`
2. Patch the existing repo data so that packages depending on cuDNN has a correct CUDA version locked (probably we get this for free already...?) 
3. Add a migrator to remove cuDNN from the zipping and rebuild all packages that added cuDNN as a dependency
4. Once the migration is done, update the zipping in the global pinning (done by bot)

Does it make sense? Does it do the job for us?

**Comment by leofang** [comment]
@jaimergp WDYT?

**Comment by beckermr** [comment]
cc @conda-forge/core

**Comment by isuruf** [comment]
There's no cudnn=8 for older cudatoolkit, so there's no way to have a global pinning.

**Comment by leofang** [comment]
Exactly. So I was proposing we don't pin globally at all.

**Comment by isuruf** [comment]
No, we should pin packages that change ABI globally.

**Comment by isuruf** [comment]
How can you version lock, when there's `cudnn=8` and `cudnn=7` for cudatoolkit=10.2 ?

**Comment by jakirkham** [comment]
Since we are looking at making CUDA 11.0 the new minimum ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1708 ), wonder if that helps us simplify things here 🙂

**Comment by leofang** [comment]
> Which one of these should downstream packages use?

Uh, the one with newer version?

**Comment by jakirkham** [comment]
This was done in PR: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/1708

Closing as resolved
