### ISSUE TITLE
cmake fails with `{{ compiler('cxx') }}` but works with `gxx_linux-64` and `clangxx_osx-64`

### ISSUE THREAD

**Issue by dlaehnemann** [conda-forge/conda-forge-pinning-feedstock#163]
Issue:

In the [bioconda testing environment](https://bioconda.github.io/contribute-a-recipe.html#circle-ci-client-method), that [uses the conda-forge build configuration](https://bioconda.github.io/guidelines.html#c-c), when using `{{ compiler('cxx') }}`, I get the cmake error:
```
Compiler Detection
CMake Error at /opt/conda/conda-bld/lambda_1545054353812/_build_env/share/cmake-3.13/Modules/CMakeDetermineCXXCompiler.cmake:47 (message):
  Could not find compiler set in environment variable CXX:

  g++.

Call Stack (most recent call first):
  CMakeLists.txt:13 (project)


CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```
However, once I replace it with the following build requirements, cmake finds the compiler and everything works smoothly:
```
    - gxx_linux-64 # [linux]
    - clangxx_osx-64 # [osx]
```
From [the `cxx_compiler` build config of conda-forge](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/180326d1e820a27f213fd8f919a982dd608dedcf/recipe/conda_build_config.yaml#L22), I would have assumed that `{{ compiler('cxx') }}` would pull in exactly these dependencies, but the packages that look `cxx`-related that get installed in the build environment are (full list below):

```
    libgcc-ng:              7.2.0-hdf63c60_3        conda-forge
    libstdcxx-ng:           7.2.0-hdf63c60_3        conda-forge
    llvm-meta:              7.0.0-0                 conda-forge
    toolchain:              2.3.0-0                 conda-forge
    toolchain_cxx_linux-64: 2.3.0-0                 conda-forge
```

Any ideas, why the relevant packages are not pulled in? Anything obvious, that I am missing?

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
    bzip2:                  1.0.6-h470a237_2        conda-forge
    ca-certificates:        2018.11.29-ha4d7672_0   conda-forge
    cmake:                  3.13.1-h011004d_0       conda-forge
    curl:                   7.63.0-h74213dd_0       conda-forge
    expat:                  2.2.5-hfc679d8_2        conda-forge
    krb5:                   1.16.2-hbb41f41_0       conda-forge
    libcurl:                7.63.0-hbdb9355_0       conda-forge
    libedit:                3.1.20170329-haf1bffa_1 conda-forge
    libgcc-ng:              7.2.0-hdf63c60_3        conda-forge
    libssh2:                1.8.0-h5b517e9_3        conda-forge
    libstdcxx-ng:           7.2.0-hdf63c60_3        conda-forge
    libuv:                  1.24.0-h470a237_0       conda-forge
    llvm-meta:              7.0.0-0                 conda-forge
    ncurses:                6.1-hfc679d8_2          conda-forge
    openmp:                 7.0.0-h2d50403_0        conda-forge
    openssl:                1.0.2p-h470a237_1       conda-forge
    rhash:                  1.3.6-h470a237_1        conda-forge
    seqan-library:          2.4.0-0                 conda-forge
    tk:                     8.6.9-ha92aebf_0        conda-forge
    toolchain:              2.3.0-0                 conda-forge
    toolchain_cxx_linux-64: 2.3.0-0                 conda-forge
    xz:                     5.2.4-h470a237_1        conda-forge
    zlib:                   1.2.11-h470a237_3       conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>
The build system used is that of `bioconda`, with details described here:
https://bioconda.github.io/build-system.html
</details>

**Comment by dlaehnemann** [comment]
This could very well be something related to the cmake setup of the tool I am trying to package for bioconda, so here are the respective `CMakeLists.txt` files, in case anybody knows more about how they work than I do:

https://github.com/seqan/lambda/blob/lambda-v1.0.3/CMakeLists.txt
https://github.com/seqan/lambda/blob/lambda-v1.0.3/src/CMakeLists.txt

**Comment by dlaehnemann** [comment]
And another reference to where I got the working requirements (`gxx_linux-64` and `clangxx_osx-64`) from:

https://conda.io/docs/user-guide/tasks/build-packages/compiler-tools.html#compiler-packages

**Comment by dlaehnemann** [comment]
Hope this gets the right people's attention... ;) @conda-forge/conda-forge-build-setup

**Comment by jjhelmus** [comment]
What are the contents of the `conda_build_config.yaml` file in use during the build?  The default conda-forge version expands the compiler jinja into `toolchain` which is a package which activates the system compilers.  These must be installed using a system package manager.

**Comment by dlaehnemann** [comment]
The one for bioconda is at:

https://github.com/bioconda/bioconda-utils/blob/master/bioconda_utils/bioconda_utils-conda_build_config.yaml

It only adds some pins on top of the conda-forge default, so I am assuming that it defaults to the behaviour you describe. Thanks already for pointing that out!

For other recipes in bioconda, the compiler templates seem to work, so I am assuming this is either a cmake-specific problem of finding the compiler or a problem of the cmake configuration of the particular software. For the latter, I would just close this issue, but if it is something more fundamental about cmake and how it searches for compilers, it might be worth fixing (somewhere...)? Any further ideas to pinpoint this in more detail?

**Comment by dlaehnemann** [comment]
I'll close this, for now -- but at least it's documented, in case something similar turns up elsewhere...
