### ISSUE TITLE
NumPy Pinnings 2021

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/conda-forge-pinning-feedstock#1682]
Scipy just started to add upper pinning for numpy
https://github.com/scipy/scipy/blob/master/setup.py#L549
![image](https://user-images.githubusercontent.com/90008/124859645-47e51180-df7e-11eb-8728-c1e7bf061b13.png)

```
    # In maintenance branch, change np_maxversion to N+3 if numpy is at N
    # Update here, in pyproject.toml, and in scipy/__init__.py
    # Rationale: SciPy builds without deprecation warnings with N; deprecations
    #            in N+1 will turn into errors in N+3
    # For Python versions, if releases is (e.g.) <=3.9.x, set bound to 3.10
    np_minversion = '1.16.5'
    np_maxversion = '9.9.99'
    python_minversion = '3.7'
    python_maxversion = '3.10'
    if IS_RELEASE_BRANCH:
        req_np = 'numpy>={},<{}'.format(np_minversion, np_maxversion)
        req_py = '>={},<{}'.format(python_minversion, python_maxversion)
    else:
        req_np = 'numpy>={}'.format(np_minversion)
        req_py = '>={}'.format(python_minversion)
```

I wonder if we should start doing it too.

Not too sure what the right answer is, but I think it is worth discussing.

**Comment by jakirkham** [comment]
cc @conda-forge/core @rgommers

**Comment by rgommers** [comment]
I would say technically yes, it's the correct thing to do. Whether it is actually a good idea depends on whether conda/mamba are going to struggle with the upper bound (whether that means finding a solution less often, or becoming slower).

See https://numpy.org/devdocs/user/depending_on_numpy.html#adding-a-dependency-on-numpy

**Comment by jakirkham** [comment]
Well one issue I see is older versions of SciPy that don't have these constraints may get pulled in. We may need to hot-fix them to not be pulled in. Though it's not clear atm how they should be hot-fixed (IOW which NumPy versions do old SciPy versions support)

**Comment by beckermr** [comment]
@CJ-Wright can the symbol work gives us insight on this question?

> Though it's not clear atm how they should be hot-fixed (IOW which NumPy versions do old SciPy versions support)

**Comment by CJ-Wright** [comment]
Yes, but not at this moment. I expect we'll have another round on the symbol database in the near future which should increase the accuracy. I think we've had some issues with missing numpy C symbols recently. The current audit entry for scipy is [here](https://github.com/symbol-management/api-match-audit/blob/master/audit/scipy/conda-forge/linux-64/scipy-1.5.3-py38hb2138dd_0) and seems to not find the required numpy symbols at all, which most likely means that the inspection missed them in numpy. I'll try to take a look at what's going on there. (@chrisburr might have better ideas) In the meantime it does list out all the symbols detected from scipy python code that scipy expects from numpy, so there is that.

While we fix those issues, we might consider running the scipy tests in a matrix of scipy versions and numpy versions. While this wouldn't be perfect, it would at least help to reveal combinations that we would know to break. We could then try to build constraints to help deal with that.

To some extent these pins are in the eye of the beholder, python never broke API if all you wanted was something to calculate that 1+1 is 2. 

I am making this comment solely in my personal capacity and am not conveying any rights to any intellectual property of any third parties.

**Comment by isuruf** [comment]
IMO, this should be left to the individual packages like scipy.

Issue is that say we are building with numpy N and N+3 comes out. Then we have to build with either N+1 or N+2 or N+3. If we select N+1, then we support all numpy versions that are possible. With this scheme we'll be building packages for each and every numpy version.
This is fine for packages with regular updates like scipy because we aren't building scipy for each and every numpy version.
For packages without regular updates, we'll be building for each and every numpy update which is going to be a lot of package rebuilds.

**Comment by rgommers** [comment]
> Issue is that say we are building with numpy N and N+3 comes out. 

Logic is slightly different:
- Right now we're building against numpy 1.17
- Current version is numpy 1.21 (this is `N`)
- So scipy built now would have an upper bound `<1.24.0` (this is `N+3)`

So the valid range at runtime is 7 minor versions of numpy.

**Comment by isuruf** [comment]
Thanks for the clarification. That's not a distinction that conda-build understands. So, it'll have to be done per package.

**Comment by hmaarrfk** [comment]
i thinj we got ti a conclusion
