### ISSUE TITLE
Migrate latest pinnings from old pinning script

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-pinning-feedstock#2]
This is a reminder to migrate the latest content from the [pinning script]( https://github.com/conda-forge/conda-forge.github.io/blob/master/scripts/pin_the_slow_way.py ) to here.

cc @conda-forge/core

**Comment by scopatz** [comment]
Are there tools for updating the pins in a recipe's meta.yaml from this data structure?

**Comment by jakirkham** [comment]
The plan is feedstocks will use a setting\* with `conda-build` 3 that will integrate the configuration file in this package into every build. Maintainers will not need to manually pin dependencies in feedstocks as this pinning will automatically be included. This will combine any information the maintainers specify in the recipe.

A different, but related, question is how can we automate the rebuilding of packages when pinnings change in this listing? ATM I don't have any good intuition for how this will work. Mainly because batching such a process would be too slow and get rate limited too quickly. Any webservice approach would have to track recipes that use these particular dependencies somehow (i.e. in a database). We would need to give some thought on where this database lives, how we access it, and how we update it, etc. There are likely many other ideas we could contemplate that I have not considered above. TL;DR this is a topic that will require further exploration.

\* -  Specifics under discussion in PR ( https://github.com/conda-forge/conda-smithy/pull/625 ).

**Comment by isuruf** [comment]
> A different, but related, question is how can we automate the rebuilding of packages when pinnings change in this listing? 

That's easy. Just do a `conda smithy rerender` and if it changes, then it needs to be rebuilt

**Comment by jakirkham** [comment]
For one package sure, the question I was contemplating is the following. If we change the pinning of a package (say `sqlite`), how do we automatically send out PRs to all affected feedstocks?

**Comment by isuruf** [comment]
Fixed in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/7
