### ISSUE TITLE
Move windows VS2015 and VC14 pins

### ISSUE THREAD

**Issue by mariusvniekerk** [conda-forge/conda-forge-pinning-feedstock#200]
Anaconda has moved over from vs2015 to vs2017 with no ill effects suffered.

This would for us be a simple change to the vs version that is used to build a package.  This does NOT require that these packages need to be recompiled as the vs2017 runtime is backwards compatible with vs2015.

The change needed is to move vs2015 to vs2017 and vc14 to vc14.1

Moving our default windows compiler forward would allow a simpler easier transition to vs2019 when that releases later in 2019.

**Comment by isuruf** [comment]
It's not simple. Needs changes in conda-smithy, staged-recipes for appveyor as the current appveyor image we use don't have VS2017 installed and the VS2017 image doesn't have VS2008 installed.

**Comment by isuruf** [comment]
> Anaconda has moved over from vs2015 to vs2017 with no ill effects suffered.

I'd like to hear more details about this.

**Comment by mariusvniekerk** [comment]
We'd likely want to pair this with a smithy change to split VC9 and VC14+ into different platforms so that we can keep VC9 only on appveyor and VC14+ on azure

**Comment by jakirkham** [comment]
We may want to add VC 14.1 and keep VC 14.0 around. As we have considerably more recipes to think about, we need to prepare for the possibility that not everything works cleanly on VC 14.1.

**Comment by isuruf** [comment]
Are static libraries compatible? https://bugs.python.org/issue31340 seems to suggest that they are not.

**Comment by msarahan** [comment]
We switched in late September: https://www.google.com/url?q=https://github.com/AnacondaRecipes/aggregate/commit/9eb99ab8c92384b0937f0008e6ec2478c5652143&sa=D&source=hangouts&ust=1551898031832000&usg=AFQjCNGkFj5dSVEqPnSxZfy-zi76-Id8Pg

We have had no compatibility issues mixing new packages with old ones.  Only the newest vs2015_runtime package is used for runtimes.  We initially had dumb metadata problems with our package pinnings, but those are worked out.  The vc package pins need to follow the normal ``>=current,<next major``, so something like ``>=14.1,<15.0a0``

**Comment by jakirkham** [comment]
Any other thoughts on this? At least from a usability standpoint, Azure is significantly faster to run builds, which seems like a very good reason to move forward here.

**Comment by isuruf** [comment]
@msarahan, did you rebuild your packages or did you just switch?

https://docs.microsoft.com/en-us/cpp/porting/binary-compat-2015-2017?view=vs-2019 has

> The only exception to this rule is that static libraries or object files that are compiled with the /GL compiler switch are not binary compatible.

**Comment by CJ-Wright** [comment]
Is this fixed? @beckermr

**Comment by beckermr** [comment]
yes
