### ISSUE TITLE
Pin `libzlib` as well as / instead of `zlib`

### ISSUE THREAD

**Issue by jmarshall** [conda-forge/conda-forge-pinning-feedstock#2000]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

The zlib runtime was recently (conda-forge/zlib-feedstock#52) split into a new `libzlib` subpackage. This repository's _recipe/conda_build_config.yaml_ lists pinning for `zlib`; does it need to be updated to list a pinning for `libzlib` instead / as well?

I noticed while developing an update to a package I help maintain that zlib no longer contributed to the package hash (see also [previous build](https://circleci.com/api/v1.1/project/github/bioconda/bioconda-recipes/161144/output/107/0?file=true&allocation-id=60e833185cf4e70d41c160df-0-build%2F4D55BB4B) in which it did — scroll to the bottom):

```
14:13:56 BIOCONDA INFO (OUT) INFO :: The inputs making up the hashes for the built packages are as follows:
14:13:56 BIOCONDA INFO (OUT) {
14:13:56 BIOCONDA INFO (OUT)   "htslib-1.13-ha0adc58_4": {
14:13:56 BIOCONDA INFO (OUT)     "recipe": {
14:13:56 BIOCONDA INFO (OUT)       "CONDA_BUILD_SYSROOT": "",
                                   [… no  "zlib": "1.2"  as previously …]
14:13:56 BIOCONDA INFO (OUT)     }
14:13:56 BIOCONDA INFO (OUT)   },
```

It appears from the comment at https://github.com/conda/conda-build/blob/174ed2000f5a7ac05d1c743bb38f4a40d647e6bb/conda_build/metadata.py#L1294-L1299 that this may be because `libzlib` does not appear in the relevant _conda_build_config.yaml_, which I believe is the one from this repository.

**Comment by isuruf** [comment]
You can't use `libzlib` standalone in `host`. You have to use `zlib` in `host` which means it will be used in the hash.
