### ISSUE TITLE
openblas 0.3.5 ?

### ISSUE THREAD

**Issue by jschueller** [conda-forge/conda-forge-pinning-feedstock#201]
why is openblas still pinned to 0.3.3 while it has been updated to 0.3.5 for aarch/ppc ?

**Comment by mariusvniekerk** [comment]
because we simply don't have an old enough openblas for those architectures

**Comment by jschueller** [comment]
I mean, we could update to 0.3.5 for x86

**Comment by jakirkham** [comment]
@isuruf, is this still relevant given the BLAS/LAPACK changes?

**Comment by hmaarrfk** [comment]
We should move up the pin for ppc64le given the fact that 0.3.6 fixed a few bugs that caused segfaults in Scipy.

**Comment by scopatz** [comment]
go for it
