### ISSUE TITLE
PR template is confusing

### ISSUE THREAD

**Issue by saraedum** [conda-forge/conda-forge-pinning-feedstock#2357]
Is there some way to replace the PR template for this feedstock?

It currently reads:

```

<!--
Thank you for your pull request.
Below are a few things we ask you kindly to self-check before getting a review. Remove checks that are not relevant.
-->
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

<!--
Please note any issues this fixes using [closing keywords]( https://help.github.com/articles/closing-issues-using-keywords/ ):
-->

<!--
Please add any other relevant info below:
-->

```

I believe that almost none of this applies here.

**Comment by jakirkham** [comment]
The templates are pulled from [the org's `.github` repo]( https://github.com/conda-forge/.github ). If we added our own template here, it should override the org one.

Though one thing we should check is whether `conda-smithy` will try to remove the template from the feedstock or keep it.

**Comment by jakirkham** [comment]
cc @conda-forge/core (in case others have thoughts here 🙂)

**Comment by beckermr** [comment]
All of those items apply except for the build number bump. I'm not sure a PR to special case this one is really worth it. Happy to accept work though if it is easily maintained.

**Comment by saraedum** [comment]
I don't think these apply @beckermr:
```
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.
```

**Comment by beckermr** [comment]
Rerender and license file apply. Those things may not change much, but they do apply.

**Comment by saraedum** [comment]
How would the pinning feedstock require a license file to be packaged?

**Comment by beckermr** [comment]
> Though one thing we should check is whether conda-smithy will try to remove the template from the feedstock or keep it.

Smithy will remove the template which is why this is non-trivial to fix.

**Comment by saraedum** [comment]
Ok. If this is too hard to do, then it's not worth it I think.

**Comment by beckermr** [comment]
> How would the pinning feedstock require a license file to be packaged?

The pinnings file is code and always requires a license file to be redistributed. The license file gives any person who mirrors this package the ability to redistribute, for example.

**Comment by saraedum** [comment]
Ok. I always thought that this was referring to the license of the software that is packaged by the feedstock, i.e., upstream's license.

**Comment by beckermr** [comment]
Right. This feedstock is both upstream and the feedstock. We copy in a file that conda build does not make: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/meta.yaml#L14

**Comment by jakirkham** [comment]
> Smithy will remove the template which is why this is non-trivial to fix.

Does it? Actually I wasn't sure about this and when looking at the conda-smithy code, it wasn't clear to me that it does.

In any event agree the changes to the template relevant to this feedstock are probably to minor to be worth the effort (the version number always increases as it is timestamped so the build number is always `0`)

**Comment by beckermr** [comment]
I thought it did but maybe not. We can try a PR to make sure.

**Comment by jakirkham** [comment]
Yep you are right. It removes them ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2361 ). Relevant [conda-smithy code]( https://github.com/conda-forge/conda-smithy/blob/b5aa6e651f47d0e02731d05b4041d3317fe09a2f/conda_smithy/configure_feedstock.py#L1559-L1560 ).

**Comment by isuruf** [comment]
> Smithy will remove the template which is why this is non-trivial to fix.

Adding `.github/PULL_REQUEST_TEMPLATE.md` to `skip_render` will make smithy not remove it.

**Comment by jakirkham** [comment]
Thanks for the suggestion Isuru 😄

Yep seems to work ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2361#issuecomment-1005450288 )

**Comment by jaimergp** [comment]
We have received several PRs regarding issues and PR templates, so maybe we should discuss this in the next meeting!

**Comment by jakirkham** [comment]
Interesting what were the other ones?

Sure that sounds reasonable

**Comment by jaimergp** [comment]
@BastianZim put these:

* https://github.com/conda-forge/staged-recipes/pull/17366
* https://github.com/conda-forge/conda-forge.github.io/pull/1578

**Comment by BastianZim** [comment]
Note: This is only for issues though, GitHub does not yet support those templates for PRs.

**Comment by jakirkham** [comment]
Ok though not other feedstocks wanting to customize things?

Generally the webpages and staged-recipes repos are going to want to do their own things. Also docker-images could benefit from similar treatment. This seems fine to iterate on asynchronously unless there is a specific thing we should discuss

**Comment by BastianZim** [comment]
Another note: At least staged-recipes already had a template I'm just updating it to a new version so content doesn't change. 

This could probably be propagated to others as well but as a note of caution: GitHub does say that they're in beta. GitHub is using them themselves so I think they're stable enough but just wanted to mention it.
