### ISSUE TITLE
about/home is outdated in recipe

### ISSUE THREAD

**Issue by teake** [conda-forge/conda-forge-pinning-feedstock#248]
Issue: about/home is outdated in recipe

The metadata pointing to the documentation has an outdated url: https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/bfb5832b7445143ff6bf22f3f819dd9fedf18211/recipe/meta.yaml#L25

This should be either be 

- https://conda-forge.org/docs/maintainer/pinning_deps.html#globally-pinned-packages or perhaps 
- https://conda-forge.org/docs/maintainer/infrastructure.html#conda-forge-pinning.

I'm not sure if this justifies a PR and rerender on its own, so perhaps it's possible to sneak this in with another PR?

**Comment by jakirkham** [comment]
Slight preference for the second option or just linking to this repo itself. No strong feelings though.

Feel free to send a PR.
