### ISSUE TITLE
GStreamer pinning is inconsistent

### ISSUE THREAD

**Issue by kuepe-sl** [conda-forge/conda-forge-pinning-feedstock#2546]
The regro-cf-autotick-bot recently upgraded GStreamer to version 1.20.

This involved a rebuild of the [main packaged](https://github.com/conda-forge/gstreamer-feedstock/commit/fd68be4cc95b781b2fe7f7c1adab51dbcd221736) and a update to its [pinning](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2484).

However, what it missed was the pinning of the *base plugin*, which has a separate pinning entry. This causes an inconsistent pinning between the GStreamer application and the plugins in the rendered ci\_support files:

```yaml
gst_plugins_base:
- '1.18'
gstreamer:
- '1.20'
```

I think the optimal way would be to have the plugins and base versions pinned to the same version.
Do we even need separate pinning specs for those two packages?

**Comment by hmaarrfk** [comment]
For now, can we migrate `gst_plugins_base`?

I think instead of using `gst_plugins_base` normal pinnings in the recipe, you could use `
```
- gst_plugins_base  {{ gstreamer }}
```

or even, no pinning at all!

**Comment by hmaarrfk** [comment]
I have a feeling we can remove the global pinning on `gst_plugins_base`

https://github.com/conda-forge/gstreamer-feedstock/blob/master/recipe/meta.yaml#L104

I want to let others chime in before. Maybe there is some recipe that depend son the "plugins" only??? that would be strange.

**Comment by hmaarrfk** [comment]
Did you accidentally merge
https://github.com/conda-forge/gst-libav-feedstock/pull/9

I think we can also edit the migrator.

Can you submit a PR for it?

**Comment by hmaarrfk** [comment]
Thanks for your help resolving this!

users facing this issue should rerun the bot
