### ISSUE TITLE
Fix pin_run_as_build for mpich and openmpi

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-forge-pinning-feedstock#2596]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

Because of https://github.com/conda-forge/conda-smithy/pull/1601, these are now added to feedstocks,
but max_pin is wrong here.

cc @beckermr

### Installed packages

```shell
a
```

### Environment info

```shell
a
```

**Comment by beckermr** [comment]
What's the bug? Feedstocks have pin run as build locally and that should be removed. Afaik we do not need it here since we have run exports.

**Comment by isuruf** [comment]
Nvm, there's no bug here
