### ISSUE TITLE
Dropping Python 3.7

### ISSUE THREAD

**Issue by dopplershift** [conda-forge/conda-forge-pinning-feedstock#2623]
We've reached a point where the [NEP29 suggestion](https://numpy.org/neps/nep-0029-deprecation_policy.html#support-table) for dropping 3.7 (December 2021) is much different from the [official EOL](https://www.python.org/downloads/) (June 2023). We probably should decide what the policy is actually going to be, since it's [becoming a relevant question](https://github.com/conda-forge/pyproj-feedstock/pull/117) for some builds.

#1947 seemed to indicate some confusion on whether we're following NEP29 or not.

**Comment by hmaarrfk** [comment]
I thought we had this discussion and an important point was to ensure that we worked with the non-scientific community as well:
https://github.com/conda-forge/conda-forge.github.io/issues/1616

**Comment by dopplershift** [comment]
Thanks, I had forgotten about that issue. I think there is still an issue with actually firmly establishing what our schedule/policy will be going forward. The issue I linked above is a practical case of:
1. Needing to rebuild an older version against our updated pins due to upstream moving on
2. Confusion about whether we're following NEP29 or not

So while that issue indicates we shouldn't drop it now, there's still a question of: when are we dropping 3.7? What are we doing when 3.11 comes out? (Beta 1 drops first week of May, official release 5 months later)

**Comment by jakirkham** [comment]
Typically we've dropped an old version when adding a new one.

**Comment by chrisburr** [comment]
I don't think we necessarily need a formal policy for this do we? In the case of Python 3.6 it made sense as end of life was close and it was an issue for the OpenSSL migration (only 3.7+ supports OpenSSL 3).

When 3.11 is released we might want to reduce the size of the build matrix, especially for ppc64le/aarch64. That said, I'd also be happy with keeping it for another year given that Python is moving towards having 5 years of support and one release per year. Especially as it seems to [be getting a decent number of downloads for the latest patch](https://anaconda.org/conda-forge/python/files?version=3.7.12).

Regardless, if an issue arises that causes Python 3.7 support to become annoying we should keep the option for dropping it sooner.

**Comment by jakirkham** [comment]
Not a formal one, but informally we have tended to keep 3 Python versions around and drop the oldest one when adding a new one. There may be other reasons like approaching EOL or other assessed costs.  The reason for this informal policy is as you say keeping the build matrix reasonable.

Individual packages as always can drop support for things they no longer support or things that cause issues.

**Comment by isuruf** [comment]
As discussed in the core meeting today, let's drop 3.7 when 3.11 comes out and we start the migration in October. We can make an announcement and if people can voice their concerns in this issue.

**Comment by jakirkham** [comment]
Submitted PR ( https://github.com/conda-forge/conda-forge.github.io/pull/1815 ) to announce the intention to drop Python 3.7

**Comment by bkpoon** [comment]
Will there be a way to still build Python 3.7 versions of a package on the `conda-forge` channel by modifying `conda_build_config.yaml`? We have users that use Google Colab notebooks with `condacolab` and integrating with AlphaFold (machine learning for structural biology). As of today, both are still on Python 3.7. Thanks!

**Comment by jakirkham** [comment]
@jakevdp, do you know who we should talk to about updating Google Colab's Python version?

**Comment by jakevdp** [comment]
I would ask on this issue: https://github.com/googlecolab/colabtools/issues/2165 One of the team members might be able to repond there regarding the current ETA.

**Comment by jakirkham** [comment]
Thanks for the speedy reply, Jake! 😄

Have posted a comment here ( https://github.com/googlecolab/colabtools/issues/2165#issuecomment-1285935062 ) asking for an ETA as well as outlining the situation. Others should feel free to include additional info.

**Comment by bkpoon** [comment]
It looks like the update might be intertwined with an update to the Ubuntu image (https://github.com/googlecolab/colabtools/issues/1880). I guess we'll wait and see.

We might switch to binder, but we'll miss the GPU.

**Comment by bkpoon** [comment]
No problem, our production releases use explicit conda environments and I can switch over to building on our own Azure organization if we really need to maintain Python 3.7 support for a little while longer.

**Comment by h-vetinari** [comment]
> I would ask on this issue: [googlecolab/colabtools#2165](https://github.com/googlecolab/colabtools/issues/2165) One of the Colab team members might be able to repond there regarding the current ETA.

Looking at the discussion there, this has been brought up with urgency for a while already (numpy 1.22 dropped 3.7 support almost a year ago), but the maintainers there have not responded to escalating pleas (and people cancelling their subscriptions), for about half a year, so it doesn't look too good unfortunately. But that's not something we can do anything about.

**Comment by chrisburr** [comment]
Closing as Python 3.7 was dropped from the build matrix in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3573

Existing versions will still be available for Python 3.7 and `noarch: python` packages are unaffected by this as they have their own package specific version pins. If any conda-forge package maintainers specifically need to keep Python 3.7 support they can ask on gitter for help.

**Comment by vallsv** [comment]
Hi, is there somehow a way to pinpoint some project to avoid the robot to remove python 3.7?
Any idea how could i revert a project which was already cleaned up?
Thanks.

**Comment by vallsv** [comment]
@chrisburr Hi, could you tell me what is gitter, and how could i ask to keep Python 3.7 for a specific project for now? See above.

**Comment by dopplershift** [comment]
@vallsv [Here](https://conda-forge.org/docs/orga/getting-in-touch.html) is all the documentation on contacting the conda-forge team, including Gitter.

**Comment by jakirkham** [comment]
FWIW Google Colab is now on Python 3.8 ( https://github.com/googlecolab/colabtools/issues/2165#issuecomment-1355523493 )! 🎉

**Comment by jakirkham** [comment]
Typically we drop a Python version around the same time we are adding a new one

As noted in these discussions before we have many more Python packages) than just those affected by NEP 29 (IOW outside Scientific Python/PyData ecosystem, so that policy ends up not covering those use cases

At the end of the day recipe maintainers are always able to skip Python versions and otherwise affect version constraints as needed

**Comment by h-vetinari** [comment]
> Typically we drop a Python version around the same time we are adding a new one

Thing is that python releases have been moving together due to the new 12 month cadence, as opposed to 18 month previously. We're now getting to the point where around the time we add 3.12, 3.8 still has well over a year before it's EOL (end of 2024). We may have to accept an extra python version in the build matrix...

**Comment by h-vetinari** [comment]
> to protect the integrity of the entire ecosystem

How long we maintain packages for a given python version shouldn't affect integrity. Numpy already dropped support for 3.8 in the last release and the world hadn't stopped.

Not sure what scenario you have in mind, but AFAICT it's mostly a question of CI resources whether we want to support 5 python versions at a time.

My point (not addressed to you particularly) is that previously, with an 18 month cadence, 4 releases covered 6 years of real time, and as a new release appeared, it was more than time to drop the oldest one. Now with a 12 month cadence, 4 releases only cover 4 years, and thus less than the official upstream support.

Already for dropping python 3.7 half a year before its EOL, there were people asking if we can keep or readd support. I think that's going to become even more relevant this time.

**Comment by chrisburr** [comment]
> Is the problem just that Python 3.7 was never built for osx-arm64?

Yes.
