### ISSUE TITLE
Migrator of CUDA for ppc64le and aarch64 not adding builds

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-pinning-feedstock#2650]
As observed in comment ( https://github.com/conda-forge/ucx-split-feedstock/pull/94#issuecomment-1077880022 ), PR ( https://github.com/conda-forge/ucx-split-feedstock/pull/93 ) appears not to add `aarch64` and `ppc64le`. Raising here in case we are missing something in the migrator.

**Comment by isuruf** [comment]
Closing in favour of https://github.com/regro/cf-scripts/issues/1516

**Comment by jakirkham** [comment]
Thank Isuru! 😄

**Comment by jakirkham** [comment]
Was initially wondering if this was whitespace related. Given `cf-scripts` is [including whitespace in the `name`]( https://github.com/regro/cf-scripts/blob/5a3d10f46132c7968bbd49c07dc30a9ea1d4e93f/conda_forge_tick/auto_tick.py#L551 ) whereas here we've dropped the whitespace

https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/057bfe408349777847a29ae7795da46ab5189c0e/recipe/migrations/cuda_112_ppc64le_aarch64.yaml#L15-L16

Though maybe that is a red herring

**Comment by isuruf** [comment]
Hmm, that might be the issue actually

**Comment by jakirkham** [comment]
`wait_for_migrators` was updated in PR ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2651 )

Rerunning the `ucx-split` migration PR to see how things go

**Comment by jakirkham** [comment]
Just got the new migration PR ( https://github.com/conda-forge/ucx-split-feedstock/pull/95 ) though it seems to be listing the old upstream migration name. Not sure what we are missing

**Comment by jakirkham** [comment]
Had merged the arch migrator PR earlier. Recently the CUDA arch migration PR ( https://github.com/conda-forge/ucx-split-feedstock/pull/98 ) was submitted. So seems the ordering of PRs is now working as expected.

Should note this is true as long as the feedstock is already in `arch_rebuild.txt`. If that is not the case, then the arch migration is considered done and a CUDA arch migration PR will be opened (as there is nothing to wait for).

Anyways going to close as this seems to be behaving as expected now. Thanks Isuru for all the help here 😄
