### ISSUE TITLE
CUDA migrator for ppc64le/aarch64 not run

### ISSUE THREAD

**Issue by leofang** [conda-forge/conda-forge-pinning-feedstock#2679]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

@kkraus14 and I saw that manually applying the migrator from #2527 would fail, likely because of a conflict with the global pinning (not sure): https://github.com/conda-forge/cub-feedstock/pull/17#issuecomment-1082005780. 

Also, almost all CUDA-dependent feedstocks are not yet hit by this migrator, so something is off.

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by jakirkham** [comment]
There are 3 steps with the migration (shown with `ucx` below):

1. Feedstocks need to be added to [`arch_rebuild.txt`]( https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/d98635788521b574bc17e030bda7c187257a870f/recipe/migrations/arch_rebuild.txt#L37 )
2. Other archs need to be enabled in a PR ( https://github.com/conda-forge/ucx-split-feedstock/pull/97 ) (bot or manual)
3. The migrator from PR ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2527 ) needs to be applied ( https://github.com/conda-forge/ucx-split-feedstock/pull/99 )

For CUDA only PRs step 2 will essentially be a no-op (configuration changes, but no build changes). One could combine steps 2 & 3 into a single PR if preferred.

**Comment by jakirkham** [comment]
Should add currently we are having some issues with some of the Docker images. Please see issue ( https://github.com/conda-forge/docker-images/issues/208 ) for details.

**Comment by leofang** [comment]
Thanks, John!

> 1. Feedstocks need to be added to [`arch_rebuild.txt`](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/d98635788521b574bc17e030bda7c187257a870f/recipe/migrations/arch_rebuild.txt#L37)

I have no idea this file exists! Apparently the CF doc could be improved... 😉

> For CUDA only PRs step 2 will essentially be a no-op (configuration changes, but no build changes). One could combine steps 2 & 3 into a single PR if preferred.

Other feedstocks aside for the moment, we are hitting a different situation in https://github.com/conda-forge/cub-feedstock/pull/17. There, we already had 2 & 3 done in the single PR as you suggested, and we saw this CI error:
```
RuntimeError: Solver could not find solution.Mamba failed to solve:
 - make
 - cuda_linux-aarch64 11.2.*
 - cmake >=3.15
 - gcc_linux-aarch64 10.*
 - gxx_linux-aarch64 10.*

with channels:

The reported errors are:
- Encountered problems while solving:
-   - nothing provides requested cuda_linux-aarch64 11.2.*
- 
```
The package `cuda_linux-aarch64` does not make any sense (and the same error happens with ppc64le too).

**Comment by leofang** [comment]
> > 1. Feedstocks need to be added to [`arch_rebuild.txt`](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/d98635788521b574bc17e030bda7c187257a870f/recipe/migrations/arch_rebuild.txt#L37)
> 
> I have no idea this file exists! Apparently the CF doc could be improved... 😉

Tracked in https://github.com/conda-forge/conda-forge.github.io/issues/1668.

**Comment by jakirkham** [comment]
Thanks! Undoubtedly documentation can be improved. Some folks are working on docs generally atm. If we are able to scope that issue well enough, we can likely find an eager participant that can help us include the needed doc changes

As to the solver error, think we have a bug in the migrator. Please see this comment ( https://github.com/conda-forge/cub-feedstock/pull/17#discussion_r839220498 ).

**Comment by jakirkham** [comment]
Just a note, we added a few more feedstocks to the arch rebuild in PR ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2681 ).

**Comment by jakirkham** [comment]
Are we good to close this issue Leo or are there other things we should be following up on?

**Comment by leofang** [comment]
Oh yes thx for reminder John. I think we're good here!

**Comment by leofang** [comment]
For the record this was fixed by #2695.

**Comment by prashantkhoje** [comment]
> There are 3 steps with the migration (shown with `ucx` below):
> 
> 1. Feedstocks need to be added to [`arch_rebuild.txt`](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/d98635788521b574bc17e030bda7c187257a870f/recipe/migrations/arch_rebuild.txt#L37)
> 2. Other archs need to be enabled in a PR ( [Arch Migrator ucx-split-feedstock#97](https://github.com/conda-forge/ucx-split-feedstock/pull/97) ) (bot or manual)
> 3. The migrator from PR ( [Added ppc64le arch migrator for different cuda versions #2527](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2527) ) needs to be applied ( [Rebuild for cuda for ppc64le and aarch64 ucx-split-feedstock#99](https://github.com/conda-forge/ucx-split-feedstock/pull/99) )
> 
> For CUDA only PRs step 2 will essentially be a no-op (configuration changes, but no build changes). One could combine steps 2 & 3 into a single PR if preferred.

Can you please share how can i go about steps 2 and 3 for other feedstocks - ptxcompiler, arrow-cpp? Please let me know docs i should refer to.
Where can i see logs of migrator run for a particular feedstock?
cc: @leofang 

Thank you,
Prashant

**Comment by jakirkham** [comment]
Those depend on the bot to do.

With `ptxcompiler`, it is blocked until its dependencies are migrated. In particular PR ( https://github.com/conda-forge/cudnn-feedstock/pull/36 ).

With `arrow-cpp`, the bot ran into some kind of error generating the migration PRs for step 3 (step 2 was done previously). So someone will need to investigate that further.

All this information can be gotten from [the status page]( https://conda-forge.org/status/ ) by looking at `aarch64 and ppc64le` migration or `cuda_112_ppc64le_aarch64` (under Other Migrations).

**Comment by prashantkhoje** [comment]
> Those depend on the bot to do.
> 
> With `ptxcompiler`, it is blocked until its dependencies are migrated. In particular PR ( [conda-forge/cudnn-feedstock#36](https://github.com/conda-forge/cudnn-feedstock/pull/36) ).
> 
> With `arrow-cpp`, the bot ran into some kind of error generating the migration PRs for step 3 (step 2 was done previously). So someone will need to investigate that further.
> 
> All this information can be gotten from [the status page](https://conda-forge.org/status/) by looking at `aarch64 and ppc64le` migration or `cuda_112_ppc64le_aarch64` (under Other Migrations).

Thank you for the inputs.
Whenever cudnn is migrated, will it trigger bot for dependent packages? If it needs manual trigger, how can it be done?

**Comment by leofang** [comment]
On the cuDNN side, the blocker is this one: https://github.com/conda-forge/cudnn-feedstock/pull/39 which is in turn blocked by https://github.com/conda-forge/zlib-feedstock/pull/54. 

Though, I am curious, based on [Isuruf's reply](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2527#discussion_r828605868) cuDNN shouldn't be a blocker for other feedstocks?

**Comment by jakirkham** [comment]
That's discussing if the migrator would work generally not whether there would be downstream dependencies that would be blocked on `cudnn` migration as is the case here

**Comment by leofang** [comment]
Then can we set it to undefined as I previously suggested? Why are we letting cudnn to block every cuda feedstock? Binding cudnn in the global pinning zip is something I never understood.

**Comment by jakirkham** [comment]
Sorry, but I think you are misunderstanding what I said above. It is is not blocking every CUDA feedstock only ones that have a dependency on `cudnn` (IOW in `requirements`).

**Comment by leofang** [comment]
Sorry for any misunderstanding I may have. I am still confused but since there's a thumbs down perhaps I should take it offline.

**Comment by jakirkham** [comment]
Happy to discuss offline
