### ISSUE TITLE
Packages to rebuild with conda-build 3

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-pinning-feedstock#27]
* [ ] arpack
* [ ] boost
* [ ] boost_cpp
* [ ] bzip2
* [ ] cairo
* [ ] curl
* [ ] dbus
* [ ] expat
* [ ] ffmpeg
* [ ] flann
* [ ] fontconfig
* [ ] freetype
* [ ] gsl
* [ ] gstreamer
* [ ] gst_plugins_base
* [ ] gdal
* [ ] geos
* [ ] giflib
* [ ] glib
* [ ] glpk
* [ ] gmp
* [ ] harfbuzz
* [ ] hdf4
* [ ] hdf5
* [ ] icu
* [ ] jpeg
* [ ] json_c
* [ ] krb5
* [ ] libblitz
* [ ] libdap4
* [ ] libevent
* [ ] libffi
* [ ] libgdal
* [ ] libiconv
* [ ] libkml
* [ ] libmatio
* [ ] libnetcdf
* [ ] libpcap
* [ ] libpng
* [ ] libprotobuf
* [ ] librdkafka
* [ ] libssh2
* [ ] libsvm
* [ ] libtiff
* [ ] libwebp
* [ ] libxml2
* [ ] lz4_c
* [ ] lzo
* [ ] metis
* [ ] mkl
* [ ] mpfr
* [ ] ncurses
* [ ] netcdf_cxx4
* [ ] netcdf_fortran
* [ ] nettle
* [ ] numpy
* [ ] openblas
* [ ] openjpeg
* [ ] openssl
* [ ] pango
* [ ] perl
* [ ] pixman
* [ ] poppler
* [ ] proj4
* [ ] python
* [ ] pyqt
* [ ] qt
* [ ] readline
* [ ] r_base
* [ ] scipy
* [ ] snappy
* [ ] sox
* [ ] sqlite
* [ ] sundials
* [ ] tk
* [ ] vc
* [ ] vlfeat
* [ ] xerces_c
* [ ] xz
* [ ] zeromq
* [ ] zlib - https://github.com/conda-forge/zlib-feedstock/pull/18
* [ ] zstd

cc @conda-forge/core

**Comment by isuruf** [comment]
Note that these packages need to have `run_exports` added in the rebuild

**Comment by CJ-Wright** [comment]
Should we write a one off script for this?

**Comment by jakirkham** [comment]
We could. One issue is some of these depend on each other. So we would need to walk through the graph. Though I'm sure something you already have could be retooled to do this if that is what you are asking. ;)

**Comment by CJ-Wright** [comment]
Sure, somethings are in [cycles](https://github.com/regro/cf-graph/blob/master/cycles.txt) which would make walking the graph rough. But that could be possible for most of the packages with networkx.
```python
import networkx as nx
g = nx.read_gpickle('graph.pkl')
order = nx.topological_sort(g)
```
Order will be a list of feedstock names in topological order (things earlier in the list are depended on by things later in the list). We may need to create a sub graph which excises the cycles out.

If there is a function that operates on the `meta.yaml` and produces something with `run_exports` then this shouldn't be too hard (I think).

**Comment by mingwandroid** [comment]
I believe you need to build everything necessary for miniconda first. I can give you that list in the correct order if you want it (but you'll have some cycles in your deps graph).

**Comment by msarahan** [comment]
@isuruf make sure you pull recipes from anacondarecipes.  We have already done many of these, and it will save you a lot of time in adding the run_exports info.

**Comment by isuruf** [comment]
@msarahan, thanks. I assume https://github.com/AnacondaRecipes/aggregate/issues/39 is okay.

@mingwandroid, we want to do this step-by-step. First step will be to add run_exports and switch to conda-build=3, and then after we know conda-build=3 works with conda-forge infrastructure, do the rebuild of all packages. So in the first step, we'll only need to rebuild packages that require `run_exports` in their order.

**Comment by mingwandroid** [comment]
I think it will be a lot easier to do this all at once. We have the recipes in a state now where you need cb3, run_exports and the new compilers. Generally speaking a single commit makes all of those changes to each.

**Comment by isuruf** [comment]
Yes, I know, but that's going to take some time and I don't want to drag switching any longer.

**Comment by jakirkham** [comment]
There were also some concerns raised in the core meeting (one before last) about how to handle rebuilding everything at once given packages built with the new compilers would not be compatible with packages built with the old compilers. While some ideas were floated, I don't think we had a clear agreed upon plan to handle rebuilding with the new compilers. It would be good to have that so that conda-forge doesn't wind up in a semi-broken state.

**Comment by msarahan** [comment]
Yes, we need that, for sure.  We can build the packages here pretty quickly.  We may want to create a repo to hold submodules that point to the new recipes at a particular commit or branch.  With that recipe collection, we can build out everything in a pretty straightforward way.

**Comment by minrk** [comment]
What are the criteria for this list? mpich/openmpi/petsc/fenics etc. will also need rebuilds with the new compilers.

**Comment by jakirkham** [comment]
This list is only regarding rebuilding packages that are generally pinned with `conda-build` 3. It’s not related to new compilers (though there is some discussion about them here).

**Comment by minrk** [comment]
Gotcha, thanks

**Comment by looooo** [comment]
is there any plan how and when to move to conda-build3?

**Comment by msarahan** [comment]
First stab looking at which recipes need to be transferred (PR from AnacondaRecipes to CF), which don't exist on AnacondaRecipes, and which have naming conflicts that need resolution:

## Migrate (PR recipe from AnacondaRecipes to CF):

scipy  (need to resolve mkl/nomkl difference between CF and defaults)
pango
snappy
libpng
openssl
qt
perl
icu
hdf5
ncurses
jpeg
fontconfig
curl   (AnacondaRecipes splits this into curl (executable) and libcurl (headers, libs))
libiconv
tk
cairo
openjpeg
libdap4
mpfr
openblas
zlib
numpy   (need to resolve mkl/nomkl difference between defaults and CF)
hdf4
gsl
libffi
lzo
xz
libxml2
krb5
libprotobuf
pixman
sqlite
harfbuzz
poppler
gmp
expat
libtiff
readline
libssh2
glib
zeromq
ffmpeg
freetype
geos
libevent
proj4
python
bzip2
libkml
mkl - part of repack recipe on AnacondaRecipes with openmp and mkl-devel outputs
dbus
giflib
pyqt

## Transfer (recipes not on AnacondaRecipes; need to be forked or PR'ed to CF from personal repo):

glpk
arpack
vlfeat
librdkafka
zstd
libpcap
flann
metis
libwebp
libmatio
sundials
libsvm
nettle
libblitz
netcdf_cxx4
sox
netcdf_fortran

## Name differences:
| AnacondaRecipes        | Conda-forge          |
| ------------- |:-------------:|
| r-base      | r_base |
| lz4-c      | lz4_c |
| json-c      | json_c |
| xerces-c  | xerces_c |

## Consolidated recipes:
| AnacondaRecipes        | Conda-forge          |
| ------------- |:-------------:|
| vs20??     | vc, vs20??_win-64  |
| gstreamer     | gstreamer, gst_plugins_base  |
| boost     | boost, boost_cpp, libbboost, boost-python  |
| gdal (TODO)     | gdal, libgdal  |

**Comment by msarahan** [comment]
## topo-sorted "migrate"

zlib
bzip2
ffmpeg
libpng
xz
icu
libxml2
expat
libkml
libffi
glib
gstreamer
sqlite
openssl
jpeg
freetype
fontconfig
dbus
qt
ncurses
readline
proj4
libtiff
openjpeg
libssh2
curl
pixman
cairo
poppler
hdf5
hdf4
libnetcdf
libdap4
giflib
geos
libgdal
tk
krb5
zeromq
libiconv
perl
gsl
libprotobuf
mkl
python
numpy
scipy
pyqt
lzo
boost
gdal
openblas
gmp
libevent
snappy
harfbuzz
pango
mpfr

**Comment by bgruening** [comment]
Can we close this one?
