### ISSUE TITLE
Increase PyPy PR limit

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-forge-pinning-feedstock#2735]
### Comment:

It's currently set to 1, but maybe we can increase it now that we have fixed common problems.

cc @mattip

**Comment by jakirkham** [comment]
cc @beckermr

**Comment by mattip** [comment]
+1 from me, at least until we hit more roadblocks.

**Comment by beckermr** [comment]
https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2738
