### ISSUE TITLE
Should `boost-cpp` be `boost_cpp` in the pinnings

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/conda-forge-pinning-feedstock#2844]
https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/1db33ddb69c9861e9e010322d4c86434a805e97d/recipe/conda_build_config.yaml#L191

This seems like a bug.

**Comment by jakirkham** [comment]
Interesting. That seems to be how other things in that list (like [`r-base`]( https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/1db33ddb69c9861e9e010322d4c86434a805e97d/recipe/conda_build_config.yaml#L301 )) are handled.

That said, would have thought the same thing that this would `_` as [it is elsewhere]( https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/1db33ddb69c9861e9e010322d4c86434a805e97d/recipe/conda_build_config.yaml#L389 ).

**Comment by isuruf** [comment]
No, that's how conda-build works.
