### ISSUE TITLE
Pin arrow?

### ISSUE THREAD

**Issue by CJ-Wright** [conda-forge/conda-forge-pinning-feedstock#287]
It seems that Arrow might not be stable?
https://github.com/conda-forge/arrow-cpp-feedstock/blob/master/recipe/meta.yaml#L18
https://github.com/conda-forge/staged-recipes/pull/9733/files#diff-fc5dcbad24c4fe2acd3b4ac6b9c0f9a5R6

**Comment by jakirkham** [comment]
cc @conda-forge/arrow-cpp @raydouglass @mike-wendt @kkraus14

**Comment by CJ-Wright** [comment]
xref: https://github.com/lvc/upstream-tracker/issues/77

**Comment by pitrou** [comment]
What do you mean "not stable"? If you're talking about the ABI, then yes, Arrow moves too fast to provide any ABI guarantees.

**Comment by xhochy** [comment]
Yes, arrow-cpp should be part of the global pinning.

**Comment by CJ-Wright** [comment]
Yep, sorry I wasn't clearer. I guess that means we should pin it.

**Comment by CJ-Wright** [comment]
Anyone interested in putting in a migration yaml? I'd be happy to help out, but it would be good if someone else got some experience with the system.

**Comment by jakirkham** [comment]
Do you have some instructions for people to follow?

**Comment by CJ-Wright** [comment]
https://regro.github.io/cf-scripts/migrators.html#making-migrators

**Comment by CJ-Wright** [comment]
Please let me know if that is not enough/where the docs could be improved.

**Comment by CJ-Wright** [comment]
https://abi-laboratory.pro/?view=timeline&l=apache-arrow

**Comment by CJ-Wright** [comment]
Also adding a new pin is the reverse of this https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/273/files#diff-75576eba2a574dd4bce625fa345716b9

**Comment by jakirkham** [comment]
What is `migration_ts`?

**Comment by CJ-Wright** [comment]
The timestamp of the migration, you can use your `time.time()` from python. It is there to make certain that the yaml files are applied in order.

**Comment by jakirkham** [comment]
Would add that to the docs. ( https://github.com/regro/cf-scripts/issues/636 )

**Comment by jakirkham** [comment]
Closing as this is done. Please reopen if I missed something.
