### ISSUE TITLE
Versioned libraries and pinning

### ISSUE THREAD

**Issue by giacomov** [conda-forge/conda-forge-pinning-feedstock#29]
(moved from https://github.com/conda-forge/staged-recipes/issues/5355)

This might be a beginner's question, but I couldn't find any documentation on this problem, although I saw issues open about this (like https://github.com/conda-forge/staged-recipes/issues/475).

When I build a C++ package, it links to whatever version of a library gets pulled by conda build. So let's say it links my products to `libCLHEP.so.2.2.0.8`.

If a user downloads the package and gets a newer version (say `libCLHEP.so.2.2.0.9`), then the link breaks.

Of course, I can fix this by pinning to a specific library version in my `meta.yaml` file, but this is overly restrictive. In fact, my software can work with say any CLHEP >= 2.2. But adding that to meta.yaml will not work because the links happens with the versioned library at build time.

I looked for some kind of flags for the linker so that it links against libCLHEP.so instead of libCLHEP.so.2.2.0.8 but couldn't find one...

how can I solve this problem?

**Comment by dougalsutherland** [comment]
Most software doesn't make such specifically-versioned libraries like `libCLHEP.so.2.2.0.8`, or at least those aren't what gets used by default. You'll want to link to e.g. `libCLHEP.so.2.2` if it exists. Telling the linker to do that will depend on the build software, but e.g. `-l:libCLHEP.so.2.2` should force that.

**Comment by giacomov** [comment]
Thanks! I might have got a weird example of a library, but my question is more general than the CLHEP library.

Is there a way to link to `libCLHEP.so` instead, so that the linking will work with `libCLHEP.so.2.2`, `libCLHEP.so.3` and so on... In other words, what is the appropriate linking so that a specification like `CLHEP >=2` in `meta.yaml` will work when CLHEP is a C++ package?

**Comment by dougalsutherland** [comment]
Yeah, just `-l:libCLHEP.so` should work.

**Comment by isuruf** [comment]
What does` objdump -p /path/to/libCLHEP.so | grep SONAME` give you?

**Comment by giacomov** [comment]
```
~ >  objdump -p $CONDA_PREFIX/lib/libCLHEP.so | grep SONAME
SONAME               libCLHEP-2.4.0.2.so
```

**Comment by isuruf** [comment]
Okay. that means the library authors are setting the soname to the patch release. This is reflected in the downstream binaries. Your options,
1. Use patchelf to modify `SONAME` of `libCLHEP-2.4.0.2.so`.
2. Use patchelf to modify link name of the downstream libraries and binaries.
3. Open a discussion with upstream about using a better soversion if they are not breaking ABI every patch release.

**Comment by giacomov** [comment]
ok, thanks!
