### ISSUE TITLE
Bump ffmpeg to 4.1???

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/conda-forge-pinning-feedstock#294]
https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/885cccbf25790b63219f763a622d52b638179cd7/recipe/conda_build_config.yaml#L364

https://github.com/conda-forge/opencv-feedstock/issues/188#issuecomment-537324575

This seems to be causing issues since opencv is using 4.1 instead of 4.0

cc @farleylai

**Comment by CJ-Wright** [comment]
Can you put up a migration yaml PR?

**Comment by CJ-Wright** [comment]
In progress
