### ISSUE TITLE
Bump arrow-cpp to 0.15.1

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-pinning-feedstock#321]
Recently `arrow-cpp` version `0.15.1` was published. Opening this to discuss bumping the pinning to the new patch release. Thoughts?

cc @conda-forge/arrow-cpp @kkraus14 @mike-wendt @conda-forge/core

**Comment by CJ-Wright** [comment]
We'd also need to tighten run exports?

**Comment by xhochy** [comment]
> We'd also need to tighten run exports?

Yes and yes to the pin bump.

**Comment by CJ-Wright** [comment]
Can you put up a PR to tighten run exports on the feedstock side? I'll put up a migrator yaml (although we might not merge it yet, I'm still putting out some fires associated with py38)

**Comment by xhochy** [comment]
run_exports: https://github.com/conda-forge/arrow-cpp-feedstock/pull/108

**Comment by jakirkham** [comment]
I'm looking at some of the packages that use `arrow-cpp` and they all seem to have their own way of constraining the version. Raised a couple issues (linked below for context). Though this seems to be the case for all packages using `arrow-cpp` today. I think before we upgrade it would be good to get all packages in conda-forge using `arrow-cpp`'s `run_exports`. Otherwise bumping the pinning doesn't have much affect. We probably still need to follow this by pulling some packages that have pinnings that are not constrained well enough. Though this should put us on the path of aligning everything and making future upgrades smoother.

xref: https://github.com/conda-forge/parquet-cpp-feedstock/issues/56
xref: https://github.com/conda-forge/pyarrow-feedstock/issues/93

**Comment by jakirkham** [comment]
Ok, I've submitted PRs to feedstocks using `arrow-cpp` to switch them to using `run_exports`. Here's the list (they are also xref'd above).

xref: https://github.com/conda-forge/pyarrow-feedstock/pull/94
xref: https://github.com/conda-forge/turbodbc-feedstock/pull/34
xref: https://github.com/conda-forge/omniscidb-cpu-feedstock/pull/16
xref: https://github.com/conda-forge/r-arrow-feedstock/pull/12

**Comment by jakirkham** [comment]
All of the PRs listed above have been merged (excepting one which will have to be dealt with separately). Given this, have submitted PR ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/325 ) to start the migration of `arrow-cpp` to version `0.15.1`. Please take a look 🙂

**Comment by jakirkham** [comment]
Ok everything appears to have been migrated. Submitting PR ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/329 ) to close out the migration and bump the pinning to `0.15.1`.
