### ISSUE TITLE
boost178 migration needs boost-cpp

### ISSUE THREAD

**Issue by izahn** [conda-forge/conda-forge-pinning-feedstock#3402]
@beckermr thank you for merging https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2757 ! Unfortunately it looks like this migration is broken and needs to be coordinated with a migration for `boost-cpp`.

The boost 178 migration in  attempts to migrate `boost` to 1.78 but leaves `boost-cpp` pinned to 1.74. This causes two problems:

1. The migration will fail for packages that depend on both `boost` and `boost-cpp` with 
```
- package boost-1.78.0-py39hac2352c_0 requires boost-cpp 1.78.0.*, but none of the providers can be installed
```
e.g as in https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=566185&view=logs&j=696704cc-6fef-57a3-ea36-f27779b8cd5e&t=ed2e6513-0a06-519f-13f9-1e5619642f2a&l=54

2. packages that depend only on `boost-cpp` will not be migrated, and will still be pinned to `1.74`. These packages will become incompatible with packages that have been migrated to `boost=1.78`.

I'm willing to spend time helping to fix this, if someone can give me some guidance on what needs to be done. My uninformed opinion is that we don't need a `boost` global pin at all, and should be pinning and migrating `boost-cpp` instead; since `boost` depends on the exact version of `boost-cpp` the boost updates would just come along for the ride when `boost-cpp` is migrated. I know there's a long history here that led to keeping boost and boost-cpp in separate feedstocks with separate global pins, so I'm probably missing something with this analysis.

**Comment by beckermr** [comment]
We usually add both to the same migrator.

**Comment by beckermr** [comment]
So a simple pr should fix it.

**Comment by hmaarrfk** [comment]
make sure to bump the migration number too.

**Comment by izahn** [comment]
Thanks, I submitted https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3403 .
