### ISSUE TITLE
Drop win-32 here

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-forge-pinning-feedstock#36]
Dropping win-32 from conda_build_config.yaml will drop win-32 support from all future feedstocks.

cc @conda-forge/core

**Comment by jakirkham** [comment]
Copying [this from Gitter]( https://gitter.im/conda-forge/conda-forge.github.io?at=5ace39431130fe3d36c7da37 ):

> Dear all,
>
> The results of our Windows 32 support poll are in.
>
> We had 91 responses, 5 users are using Win32 and only 1 is using Win32 exclusively.
>
> We believe that this result supports our decision to stop supporting Windows 32.
> This drop will free half of our CI time on Windows and will ensure that Win64 packages are built and shipped much faster.
>
> We understand that this decision may hurt some users and we apologize for that,
> but the advantages outweigh the disadvantages.
>
> Thank you for your understanding,
>
> The conda-forge core team.

**Comment by jakirkham** [comment]
Closing as this was done in PR ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/37 ).
