### ISSUE TITLE
Adding CUDA 10.2

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-pinning-feedstock#361]
Am raising this mostly as tracking issue. Though please feel free to follow along.

* [x] Add `cudatoolkit` package for 10.2 ( https://github.com/AnacondaRecipes/cudatoolkit-feedstock/pull/2 )
* [x] Add `condaforge/linux-anvil-cuda:10.2` image ( https://github.com/conda-forge/docker-images/pull/126 )
* [ ] Create migrator for CUDA 10.2 ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/360 )
* [x] Add `cudnn` for CUDA 10.2 ( https://github.com/AnacondaRecipes/cudatoolkit-feedstock/pull/2#issuecomment-567693940 )
* [x] Migrate CUDA 10.2 packages
* [x] Close out migration

**Comment by isuruf** [comment]
According to https://docs.nvidia.com/cuda/cuda-toolkit-release-notes/index.html#cuda-general-new-features , starting with 10.1, the sonames are changed from `major.minor` to `major`. 10.2 does not add any new GPU architectures. So, what's the benefit of adding 10.2?

**Comment by mike-wendt** [comment]
10.2 adds new API features that several libraries will want to take advantage of. We at RAPIDS are working on adopting 10.2 for our next release.

**Comment by kkraus14** [comment]
>This release of the CUDA toolkit is packaged with libraries that deliver new and extended functionality, bug fixes, and performance improvements for single and multi-GPU environments.

There's also sometimes huge perf increases and other bugfixes.

**Comment by isuruf** [comment]
> There's also sometimes huge perf increases and other bugfixes.

Are these code generation improvements or library improvements? 

If the latter, https://github.com/conda-forge/nvcc-feedstock/issues/35 is enough.

**Comment by jakirkham** [comment]
> > There's also sometimes huge perf increases and other bugfixes.
> 
> Are these code generation improvements or library improvements?
> 
> If the latter, [conda-forge/nvcc-feedstock#35](https://github.com/conda-forge/nvcc-feedstock/issues/35) is enough.

Some libraries SONAMEs still change as noted in [this comment]( https://github.com/conda-forge/nvcc-feedstock/issues/35#issuecomment-567718797 ).

**Comment by leofang** [comment]
> * Add `cudnn` for CUDA 10.2

Sounds like we need to bump the pinning for cudnn again to 7.6.5.

**Comment by jakirkham** [comment]
This has been done for a while. So closing this out. Feel free to raise new issues for anything else.
