### ISSUE TITLE
google-cloud-cpp migrations not being triggered

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/conda-forge-pinning-feedstock#3795]
### Comment:

@h-vetinari -- https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3794#issue-1474706268

> Not sure why the bot doesn't open PRs for this one anymore - we already discussed this in the https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3618 for 2.3.0, and the bot didn't open one for either 2.4 or 2.5 shrug

**Comment by hmaarrfk** [comment]
I think this is https://github.com/conda-forge/status/issues/134#issuecomment-1336650568

**Comment by h-vetinari** [comment]
Not sure what changed, but the bot did open https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3917 [2.6 ] & https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4044 [2.7], so I think this issue can be closed now.
