### ISSUE TITLE
How about sorting packages in `osx_arm64.txt` ?

### ISSUE THREAD

**Issue by ivaquero** [conda-forge/conda-forge-pinning-feedstock#3800]
### Comment:

Sorting packages in `osx_arm64.txt` and `arch_rebuild.txt` can help to avoid duplicated addition.

I checked `arch_rebuild.txt` and found there were a dozen of duplicated lines.

**Comment by h-vetinari** [comment]
I'd be in favour. It would help with lookup & duplication, and it's easy to automate too

**Comment by ivaquero** [comment]
Create a PR https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4056

**Comment by hmaarrfk** [comment]
> can help to avoid duplicated addition.

This can be easily done as a test see for example the short test I added to ensure that yamls were valid.

https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3405

you could add a test that checks for duplicate entries, and cause an error.

TBH, I don't really see the problem with duplicated entries. Does it cause the bot to error?

> easy to automate too

I think this might have to be a requirement of this.

**Comment by hmaarrfk** [comment]
I think part of this is just missing documentation. I'm trying to improve that https://github.com/conda-forge/conda-forge.github.io/pull/1895

**Comment by ivaquero** [comment]
> Does it cause the bot to error?

So far I didn't see any duplicate entry raising errors. However, it seems be unnecessary to add the duplicated ones. 

It can be helpful to add an item in the task list of PR to ask contributors to check https://conda-forge.org/status before modification of these two recipe files.
