### ISSUE TITLE
pytorch pin

### ISSUE THREAD

**Issue by ngam** [conda-forge/conda-forge-pinning-feedstock#3802]
### Comment:

@hmaarrfk @h-vetinari is there anything wrong with the pytorch pin not updating? Do we need to do it manually or is it just taking a little more time?

**Comment by hmaarrfk** [comment]
https://github.com/conda-forge/status/issues/134#issuecomment-1336650568

**Comment by hmaarrfk** [comment]
yeah. kinda good since the OSX builds had failed.

I think we need to build them out by hand.
https://github.com/conda-forge/pytorch-cpu-feedstock/issues/152

I didn't realize that before merging.

I know that ALOT of my friends and colleagues still use OSX+x86
