### ISSUE TITLE
Add SDL2 stack to pinning?

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-forge-pinning-feedstock#3809]
SDL2 is already in conda-forge; it'll gain importance because it's needed for [pygame](https://github.com/conda-forge/staged-recipes/pull/19665), which itself is needed for gym, ray, modin, etc.

So far, `sdl2_{image,mixer,ttf}` pinned `sdl2 2.0.*`, but that feedstock recently made a [big](https://github.com/conda-forge/sdl2-feedstock/pull/32) version jump; turns out that this is commensurate with what upstream [did](https://github.com/libsdl-org/SDL/tags?after=release-2.24.1), i.e. going from 2.0.22 -> 2.23.* -- combined with the fact that the pinning was 2.0.* previously -- very much makes it seem like we'd actually only need to pin to major level.

Looking at the [contents](https://github.com/regro/libcfgraph/blob/master/artifacts/sdl2/conda-forge/linux-64/sdl2-2.26.1-hf1af685_1.json#L215-L305) of sdl2, it's also pretty clear IMO that this falls within the purview of the global pinning.

`sdl2_{image,mixer}` are relatively current, but ttf is [woefully](https://github.com/libsdl-org/SDL_ttf) out of date. I plan to tackle this after https://github.com/conda-forge/sdl2_ttf-feedstock/pull/8.

That way, we could get rid of the ugly pins in the `sdl2_*` packages, and eventually migrate properly (SDL3 recently kicked off development).

Thoughts @conda-forge/sdl2 @conda-forge/sdl2_image @conda-forge/core?

**Comment by h-vetinari** [comment]
Ah, forgot [smpeg2](https://github.com/conda-forge/smpeg2-feedstock), which also belongs to this space.

**Comment by h-vetinari** [comment]
> Ah, forgot [smpeg2](https://github.com/conda-forge/smpeg2-feedstock), which also belongs to this space.

Nevermind, smpeg2 has been [replaced](https://github.com/libsdl-org/SDL_mixer/blob/release-2.6.2/CHANGES.txt#L56) by mpg123, which is [already](https://github.com/conda-forge/mpg123-feedstock/) in conda-forge, but not in the global pinning.

CC @conda-forge/mpg123

PS. I guess it shows the importance of mpg123 to the sdl-stack that they're [mirroring](https://github.com/libsdl-org/mpg123) it directly.

**Comment by hmaarrfk** [comment]
Yes. All the above should have standard pinnings.

Typically i add a migrator then try to catch it when it finishes.

**Comment by h-vetinari** [comment]
> Typically i add a migrator then try to catch it when it finishes.

Given that it's been pinned to 2.0.x (now 2.x) for many years, I think we could directly add a pin to the pinning (at least sdl2 for now). That would allow us to remove the pins in the recipes, rerender, and voilà.

**Comment by hmaarrfk** [comment]
> Given that it's been pinned to 2.0.x (now 2.x) for many years, I think we could directly add a pin to the pinning (at least sdl2 for now). That would allow us to remove the pins in the recipes, rerender, and voilà.

Correct.
