### ISSUE TITLE
Timeline for closing out OpenSSL 3 migration / dropping OpenSSL 1.1.1

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-forge-pinning-feedstock#3838]
One of the longest-running migrations (and painful for the solver, see [here](https://github.com/conda-forge/conda-forge.github.io/issues/1528)) has been the one for OpenSSL 3.

However, due to the efforts of many people, this is now turning into home stretch (more below).

The reason for opening this issue is that people might not be ready for a world in which there are no more 1.1.1 builds, if only due to the sheer lengths of time it's been there.

In particular, anaconda does not yet [build](https://github.com/AnacondaRecipes/openssl-feedstock/) for OpenSSL 3, which would mean that after dropping 1.1.1, many of their packages would not be co-installable with continuing-to-be-migrated conda-forge ones anymore.

I don't know Anaconda's timeline, but the EOL for OpenSSL 1.1.1 is in 2023/09/11, so only 9 months away.
CC @chenghlee @jezdez @skupr-anaconda @AndrewVallette

## Status of remaining OpenSSL 3 PRs

(not everything shows up in the migrator [status](https://conda-forge.org/status/#openssl3); I also used the recently much-improved GH [search](https://github.com/search?q=org%3Aconda-forge+rebuild+for+openssl3++&type=pullrequests&state=open))

### Essential
* [x] https://github.com/conda-forge/qt-webengine-feedstock/pull/19
* [x] https://github.com/conda-forge/rstudio-feedstock/pull/13 
* [x] https://github.com/conda-forge/tensorflow-feedstock/pull/286

### Ready to merge
* [x] https://github.com/conda-forge/arrow-cpp-feedstock/issues/918
* [x] https://github.com/conda-forge/heavydb-ext-feedstock/pull/33
* [x] https://github.com/conda-forge/htcondor-feedstock/pull/136
* [x] https://github.com/conda-forge/htcondor-feedstock/pull/134
* [x] https://github.com/conda-forge/htcondor-feedstock/pull/128
* [x] https://github.com/conda-forge/katago-feedstock/pull/2
* [x] https://github.com/conda-forge/kubo-feedstock/pull/11
* [x] https://github.com/conda-forge/m2crypto-feedstock/pull/70
* [x] https://github.com/conda-forge/subversion-feedstock/pull/18
* [x] https://github.com/conda-forge/virtuoso-opensource-feedstock/pull/7
* [x] https://github.com/conda-forge/yarp-feedstock/pull/18

Todo:
* [ ] https://github.com/conda-forge/capnproto-feedstock/pull/32 (single failing test with OpenSSL 3)
* [ ] https://github.com/conda-forge/libpcap-feedstock/pull/14 (newly added feedstock; windows build errors)
* [x] https://github.com/conda-forge/libtins-feedstock (migrator thinks it depends on libpcap, however one is `# [osx]` and one is `# [win]` for OpenSSL)
* [ ] https://github.com/conda-forge/rb-eventmachine-feedstock/pull/4 (dependent on ruby 3 migration) 

### Problematic

Ruby 2.5 & 2.6 will very [likely](https://github.com/conda-forge/ruby-feedstock/pull/110#issuecomment-1338755202) not support OpenSSL 3
* [ ] https://github.com/conda-forge/ruby-feedstock/pull/110
* [ ] https://github.com/conda-forge/ruby-feedstock/pull/109
* [ ] https://github.com/conda-forge/nodejs-feedstock/pull/242 (this still has some users, but upstream is not compatible)

Started a ruby 3 migration:
* [x] https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2347

### Feedstocks that still pin to 1.1.1
(sidenote: loving the new GH [search](https://github.com/search?q=org%3Aconda-forge+-+%221.1.1%22+path%3Arecipe%2Fconda_build_config.yaml&type=code) [functionality](https://github.com/search?q=org%3Aconda-forge+%22-+openssl+1%22+path%3Arecipe%2Fmeta.yaml&type=code) 🤩 )
* [x] https://github.com/conda-forge/rvlib-feedstock/pull/22
* [x] https://github.com/conda-forge/tmate-feedstock/pull/16

### Abandoned / Obsolete Packages
* [x] https://github.com/conda-forge/hdf5-feedstock/pull/168 (for 1.10 branch; global pinning is already at 1.12)
* [x] https://github.com/conda-forge/mysql-connector-c-feedstock/pull/21 (5 years old; seems to have been replaced by `mysql-connector-cpp`)
* [x] https://github.com/conda-forge/postgres-xl-feedstock/pull/8 (last release ~4 years ago)
* [x] [salt](https://github.com/conda-forge/salt-feedstock/blob/main/recipe/meta.yaml#L27) (pinned to openssl 1.0.*!)

PS. There are some [grumblings](https://discuss.python.org/t/our-future-with-openssl/21486) in upstream CPython about _not_ moving to OpenSSL 3, and the cryptography devs are also [not enthusiastic](https://discuss.python.org/t/our-future-with-openssl/21486/31) about OpenSSL 3 (despite supporting it from the start, and defaulting to it nowadays). However, there are no really compelling alternatives, so assuming OpenSSL 3 stabilizes a bit in the perception of the community, it might be the least bad option after all.

**Comment by h-vetinari** [comment]
From the side of conda-forge, aside from all other concerns, there's obviously an interest in closing this migration sooner rather than later, because it keeps many feedstocks on a doubled build matrix, which is especially painful for packages that need manual builds.

**Comment by pkgw** [comment]
Considering conda-forge on its own, I would really like to declare this migration complete (or, "as complete as it's going to get") sooner rather than later — the massive build matrixing is indeed very painful, IMO. I don't understand the migration machinery super well but I'd be tempted to say that we declare it done when the "Essential" packages above are dealt with, and mop up the rest as their maintainers deal with them.

However, the status with regards to Anaconda is certainly important, and I don't think we should drop support for the 1.x series until we understand the timeline there. So hopefully at some point we'll get an update on that.

Finally, regarding CPython and cryptography, I think that's actually a bit of a red herring — it's not like they're going to stick with OpenSSL 1.x rather than 3.x, and indeed 3.x is now supported; it's just that they may wish to move away from OpenSSL altogether in the future. That would be something to deal with, but is orthogonal to the OpenSSL update.

**Comment by h-vetinari** [comment]
> Finally, regarding CPython and cryptography, I think that's actually a bit of a red herring — it's not like they're going to stick with OpenSSL 1.x rather than 3.x, and indeed 3.x is now supported

It's supported in cryptography, but incomplete in CPython. Also, there's at least some speculation about pushing 1.1.1 past its EOL:
> I think the options are:
>  * Wait and see: half the internet is in the same position as us re: openssl 1.1.1/3.0, so as the planned 1.1.1 EOL date approaches I expect some kind of consensus will develop about what to do – whether that’s pushing back the EOL date, or openssl upstream getting things together to fix 3.0, or a group coalescing to maintain 1.1.1 past the EOL or what.
>  * [...]

**Comment by jakirkham** [comment]
We discussed this at the core meeting. The main thing to discuss from our perspective is when we consider this done. Given OpenSSL 3 will become the only supported version in the Fall of 2023 and we are still migrating a few things (notably TensorFlow), we thought moving to OpenSSL 3 only by Spring of 2023 seemed like a reasonable timeline to be done, but we can pull this in sooner if the remaining pieces are in before then. Will discuss again in the New Year to see where things are and if that needs to change.

**Comment by chrisburr** [comment]
As there hasn't been a contradicting view: I'm keen to give this a little longer as I still find I have too many issues with OpenSSL 3.x for it to be usable (hopefully I'll deal with them over the next few weeks).

**Comment by jakirkham** [comment]
Yeah the general consensus at the meeting was this won't be closed until 2023. Spring 2023 seemed reasonable by most of those gathered.

Maybe it is worth spelling out the specific issues encountered so they are tracked here?

**Comment by jakirkham** [comment]
> However, the status with regards to Anaconda is certainly important, and I don't think we should drop support for the 1.x series until we understand the timeline there. So hopefully at some point we'll get an update on that.

@chenghlee could you or someone on the Anaconda side please comment on your OpenSSL 1 to 3 plans?

**Comment by chenghlee** [comment]
> could you or someone on the Anaconda side please comment on your OpenSSL 1 to 3 plans?

Anaconda is planning to kick off its repositories' OpenSSL 3.x migration in early 2023; the goal is definitely to get it done before September 2023.

**Comment by hmaarrfk** [comment]
I think i resolved the tmate issue a while back. it was a different package that had an issuie.

**Comment by h-vetinari** [comment]
> I think i resolved the tmate issue a while back. it was a different package that had an issuie.

tmate still pins openssl 1 in the recipe, so it's not done yet.

**Comment by h-vetinari** [comment]
> > I think i resolved the tmate issue a while back. it was a different package that had an issuie.
> 
> tmate still pins openssl 1 in the recipe, so it's not done yet.

On second look, those pins are only there for testing. Still, I guess we should ensure that it works for both...

**Comment by h-vetinari** [comment]
Tensorflow is finally done! 🥳 

In fact, because the manual builds there are so much work (~roughly one build per overnight run), it already preempted the closing of the migration and _only_ built for OpenSSL 3.

That leaves the ruby ecosystem, where the ruby 3 migration got started (ruby 2.x won't support OpenSSL 3), but it seems that there were some layout changes and several packages there don't build anymore.

**Comment by pkgw** [comment]
At this point in the process, it might make sense to reorganize the (very helpful!) lists at the top of this issue to more clearly separate what's done and what's left to do. As far as I can tell, the remaining to-dos are all approximately equal priority?

**Comment by pkgw** [comment]
@h-vetinari Yes, at this point I think the closing of the migration is more about a policy choice of when to start de-matrixing OpenSSL 1.1, rather than about resolving technical blockers.

OK if I edit the top post?

**Comment by h-vetinari** [comment]
> OK if I edit the top post?

Go right ahead!

**Comment by jakirkham** [comment]
Status is [here]( https://conda-forge.org/status/#openssl3 ). Looks all PRs are opened and nearly all merged.

There's a PR to close the migration ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/3892 ). Let's discuss wrapping this up there.

**Comment by h-vetinari** [comment]
> Status is [here](https://conda-forge.org/status/#openssl3). Looks all PRs are opened and nearly all merged.

For various reasons[^1], the list in the OP here is more comprehensive than what's shown on the migrator status.
 
> There's a PR to close the migration ( #3892 ). Let's discuss wrapping this up there.

Would suggest to keep it in this issue, but don't mind moving to the PR if that's what people prefer.

[^1]: e.g. the migrator will not issue PRs if the feedstock has a hard pin on OpenSSL, and I explicitly looked for those too

**Comment by jakirkham** [comment]
Question on this item from the list:

> https://github.com/conda-forge/libtins-feedstock (migrator thinks it depends on libpcap, however one is # [osx] and one is # [win] for OpenSSL)

Should we open a PR manually migrating this feedstock?

**Comment by jakirkham** [comment]
On a different list item:

> https://github.com/conda-forge/rb-eventmachine-feedstock/pull/4 (dependent on ruby 3 migration)

We now have a Ruby 3 migrator for `rb-eventmachine` ( https://github.com/conda-forge/rb-eventmachine-feedstock/pull/5 ). Have merged the OpenSSL 3 migrator into the Ruby 3 migrator. There are some build issues that need debugging

**Comment by traversaro** [comment]
> https://github.com/conda-forge/libpcap-feedstock/pull/14 (newly added feedstock; windows build errors)

This is now fixed by https://github.com/conda-forge/libpcap-feedstock/pull/18 .

**Comment by h-vetinari** [comment]
Just an FYI for anyone curious: OpenSSL 1.1.1 is end-of-life as of [today](https://mta.openssl.org/pipermail/openssl-announce/2023-September/000274.html).
