### ISSUE TITLE
Remaining items for closing qt 5.15 migration

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-forge-pinning-feedstock#3891]
Since there was no consensus about closing the PRs on abandoned feedstocks in the k*-ecosystem (see [here](https://github.com/conda-forge/conda-forge.github.io/issues/1861)), here's a manual list of the remaining to-dos before closing the qt 5.15 migration.

## Status of remaining qt 5.15 PRs

(almost everything shows up in the migrator [status](https://conda-forge.org/status/#qt515); but I also double-checked with the recently much-improved [GH](https://github.com/search?q=org%3Aconda-forge+rebuild+for+qt515++&type=pullrequests&state=open) [search](https://github.com/search?q=org%3Aconda-forge+rebuild+for+qt515+is%3Aunmerged&type=pullrequests&state=closed))

### Ready to merge
* [x] https://github.com/conda-forge/freecad-feedstock (already done even though it's listed as "waiting for parents")
* [x] https://github.com/conda-forge/pivy-feedstock (already done even though it's listed as "waiting for parents")
* [x] https://github.com/conda-forge/soqt-feedstock (already done even though it's listed as "bot error")
* [x] https://github.com/conda-forge/vitables-feedstock/pull/22

### To do
* [ ] https://github.com/conda-forge/gammaray-feedstock/pull/2 (apparently running into missing `-fPIC` of  a binutils lib)
* [ ] https://github.com/conda-forge/jkqtplotter-feedstock/pull/5 (looks like source incompatibility)
* [ ] https://github.com/conda-forge/prismatic_split-feedstock/pull/33 (fails for win+CUDA)
* [ ] https://github.com/conda-forge/py_entitymatching-feedstock/pull/6 (resolver errors due to restrictive pins)
* [x] https://github.com/conda-forge/qscreencast-feedstock/pull/12 (looks like missing only trivial recipe fixes)
* [ ] https://github.com/conda-forge/zeit-feedstock (potentially, pending https://github.com/conda-forge/zeit-feedstock/issues/1)

### Feedstocks that still pin to qt < 5.15
(sidenote: loving the new GH [search](https://github.com/search?q=org%3Aconda-forge+%22-+5.1%22+path%3Arecipe%2Fconda_build_config.yaml&type=code) [functionality](https://github.com/search?q=org%3Aconda-forge+%22-+qt+5%22+path%3Arecipe%2Fmeta.yaml&type=code) 🤩 )
* [ ] [pyqtads](https://github.com/conda-forge/pyqtads-feedstock/blob/main/recipe/meta.yaml#L33-L41) (this is the reason it's shown as `not-solvable` in the migration)

### Abandoned / Obsolete Packages
* [x] https://github.com/conda-forge/dioptas-feedstock/pull/18 (last update 3 years ago)
* [x] https://github.com/conda-forge/qtserialport-feedstock/pull/6 (still stuck on qt 5.9!)
* [x] https://github.com/conda-forge/lxqt-build-tools-feedstock/pull/6 (last update 3 years ago)
* [x] https://github.com/conda-forge/qwtpolar-feedstock/pull/13 (feedstock archived)
* [x] https://github.com/conda-forge/tomviz-feedstock/pull/50 (still stuck on python 3.7)
* [x] everything leading up to kdenlive (including PRs still listed as "waiting for parents"), see [here](https://github.com/conda-forge/conda-forge.github.io/issues/1861):
  * [x] https://github.com/conda-forge/attica-feedstock/pull/20
  * [x] https://github.com/conda-forge/karchive-feedstock/pull/18
  * [x] https://github.com/conda-forge/kcodecs-feedstock/pull/17
  * [x] https://github.com/conda-forge/kconfig-feedstock/pull/18
  * [x] https://github.com/conda-forge/kcoreaddons-feedstock/pull/18
  * [x] https://github.com/conda-forge/kdbusaddons-feedstock/pull/17
  * [x] https://github.com/conda-forge/kguiaddons-feedstock/pull/18
  * [x] https://github.com/conda-forge/ki18n-feedstock/pull/19
  * [x] https://github.com/conda-forge/kirigami2-feedstock/pull/22
  * [x] https://github.com/conda-forge/kitemviews-feedstock/pull/17
  * [x] https://github.com/conda-forge/kwidgetsaddons-feedstock/pull/18
  * [x] https://github.com/conda-forge/kwindowsystem-feedstock/pull/19
  * [x] https://github.com/conda-forge/sonnet-feedstock/pull/18

All in all, it looks like there's barely a handful feedstocks left in order to be able to close this.

CC @conda-forge/qt-main

**Comment by hmaarrfk** [comment]
I am proposing we update the pinnings for now, and leave the migration open
https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4442

**Comment by hmaarrfk** [comment]
I'm not too sure about pyqtads. I remember I helped on that one due to it being stuck for some strange reason at the time.

**Comment by h-vetinari** [comment]
> I am proposing we update the pinnings for now, and leave the migration open

I'm much in favour of updating the pinnings. I'd close the migration, as these packages are (with perhaps 2-3 exceptions) simply not being updated anymore. And as soon as someone picks them up again and rerenders, they get the new pinnings anyway.

That said, I don't really care if the migration stays open, as long as we can move forward (i.e. qt6 soon, as you mentioned in #4442).

**Comment by hmaarrfk** [comment]
Since i made the PR #4442 i had a chance to go through your notes more thoroughly, and they are quite complete. I think we should just merge and move forward. I'll close the migration in #4442

**Comment by h-vetinari** [comment]
This was closed by https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4442
