### ISSUE TITLE
Migration packages don't show up in conda-forge status

### ISSUE THREAD

**Issue by pavelzw** [conda-forge/conda-forge-pinning-feedstock#3966]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

In #3957 and #3958 (merged >24 hours ago) I added [`pathos`](https://github.com/conda-forge/pathos-feedstock) and [`forestci`](https://github.com/conda-forge/forestci-feedstock) to the osx_arm64 and arch_rebuild migrations. Since then, they don't show up in the graph on the [conda-forge status page](https://conda-forge.org/status/).

Edit: I just realized that the `pathos` package is already `noarch` but the issue for `forestci` still stands...

**Comment by dopplershift** [comment]
Isn't forestci also noarch?

**Comment by jakirkham** [comment]
Looks like [it]( https://github.com/conda-forge/forestci-feedstock/blob/a57ce9ae5a227103587aaa868ac85b6877972a80/recipe/meta.yaml#L15 )

**Comment by pavelzw** [comment]
Yes, I got confused because the [.tar.bz files](https://anaconda.org/conda-forge/forestci/files) before `0.6` indicated that had separate builds 😅
