### ISSUE TITLE
Not receiving CUDA 12 migration yet despite the status page says otherwise

### ISSUE THREAD

**Issue by leofang** [conda-forge/conda-forge-pinning-feedstock#4569]
I am looking at this page for the CUDA 12 migrator
![截圖 2023-06-12 下午12 15 55](https://github.com/conda-forge/conda-forge-pinning-feedstock/assets/5534781/514d0165-48ac-463c-9dca-8d3c916634b3)

which says pennylane-lightning-gpu has been migrated. However, we do not see the migration PR sent to [the feedstock](https://github.com/conda-forge/pennylane-lightning-gpu-feedstock). It seems something is off.

cc: @jakirkham @conda-forge/pennylane-lightning-gpu @beckermr

**Comment by beckermr** [comment]
The bot is correct. This feedstock skips any cuda version != 11.2

https://github.com/conda-forge/pennylane-lightning-gpu-feedstock/blob/main/recipe/meta.yaml#L15

**Comment by leofang** [comment]
IIUC the bot should issue the migrator, and we see no change after rerendering (because of the skip). At least that's my past impression. Perhaps things have changed now?

**Comment by leofang** [comment]
Got it, thanks Matt!
