### ISSUE TITLE
cfitsio 4.2.0 migration would require wcslib 7.12 migration

### ISSUE THREAD

**Issue by hugobuddel** [conda-forge/conda-forge-pinning-feedstock#4626]
### Comment:

There is a migration from cfitsio 4.1.0 to 4.2.0, however wcslib is kept on 7.7 which still depends on cfitsio 4.1.0.

wcslib 7.12 has been migrated to cfitsio 4.2.0 though, so using wcslib 7.12 should work. The migration to cfitsio 4.10 was accompanied by the migration to wcslib 7.7; both PR's came in on the same day (May 6 for cpl), so maybe this is a known problem with a known solution.

There are 28 packages depending on cfitsio, and 5 of the 6 "in PR" fail because these also depend on wcslib and mamba cannot solve the dependencies. E.g. 
* https://github.com/conda-forge/cpl-feedstock/pull/13 (the one I'm responsible for)
* https://github.com/conda-forge/lenstool-feedstock/pull/3
* https://github.com/conda-forge/gnuastro-feedstock/pull/31
* https://github.com/conda-forge/casacore-feedstock/pull/78
* https://github.com/conda-forge/astrometry-feedstock/pull/40

How can we proceed with upgrading to cfitsio 4.2.0? Perhaps migrate to wcslib 7.12 and cfitsio 4.2.0 at the same time? Release the wcslib pin? Is there something we as feedstock maintainers can do ourselves?

@pkgw  @conda-forge/cfitsio  @conda-forge/wcslib @conda-forge/cpl @conda-forge/astromety @conda-forge/casacore  any idea?

**Comment by hugobuddel** [comment]
Perhaps this is related to the `x.x.x` pinning in cfitsio?

https://github.com/conda-forge/cfitsio-feedstock/blob/main/recipe/meta.yaml#L19-L20
```
  run_exports:
    - {{ pin_subpackage('cfitsio', max_pin='x.x.x') }}
```

Unfortunately, at least for cpl it is required to have this x.x.x pin.

https://github.com/conda-forge/cpl-feedstock/blob/main/recipe/meta.yaml#L34-L39
```
    # cpl has a check that it requires at least the cfitsio version was built against.
    # Note that this isn't strictly necessary to add because cfitsio is pinned
    # globally in conda-forge-pinning to x.x.x anyway, meaning you will automatically
    # get the same cfitsio version at build and run time. But if cfitsio weren't
    # pinned in conda-forge-pinning, the following pin would be needed.
    - {{ pin_compatible('cfitsio', min_pin='x.x.x') }}
```

**Comment by hugobuddel** [comment]
A tangential question, apparently this migration has been going on for a while. Almost all of the 21 successful migrations were done in November 2022, and a handful in January or March. None of those successful ones had wcslib as a dependency.

It seems unlikely to be a coincidence that all 5 packages that depend on both cfitsio and wcslib are targeted by the bot today. Does the bot check whether the build will work before making a PR?

**Comment by hmaarrfk** [comment]
I think the global pin is out of sync with the run export. see https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4627

**Comment by hmaarrfk** [comment]
> Does the bot check whether the build will work before making a PR?

I feel like it used to check that it would "solve the environment".

**Comment by hmaarrfk** [comment]
try again in 1-4 hours.

**Comment by hmaarrfk** [comment]
every recipe you listed above will need a rerender

**Comment by juliotux** [comment]
Fix already working.

**Comment by hugobuddel** [comment]
Thank you @hmaarrfk, that was quick! I asked the bot to rerender the other PRs.

I think we're done here; below is an exposition why I think relaxing the wcslib dependency is fine.


I was wondering whether the wcslib pin was purposefully on 7.7 and not just 7 (chesterton's fence). For example, cpl has a runtime check that ensures it only works if you a versio of cftsio that is the same or newer than what it was compiled with. Maybe it also has such a check for wcslib (can't remember).

But even in that case it would be fine: `conda update cpl` on a system with wcslib 7.7 would try to install the latest cpl (compiled with cfitsio 4.2.0 & wcslib 7.12, but depending only on wcslib 7.x), so it would initially only try to upgrade cfitsio (and not wcslib). But since the cfitsio pin is on x.x.x, wcslib has to be upgraded as well, since only 7.12 depends on cfitsio 4.2.0.

So it is probably fine, and if not, we can perhaps migrate wcslib to 7.12 once the cfitsio migration is over.
