### ISSUE TITLE
Fix overly strict versions

### ISSUE THREAD

**Issue by isuruf** [conda-forge/conda-forge-pinning-feedstock#47]
curl `7.44` should be changed to `7` and `max_pin: x`

**Comment by jakirkham** [comment]
So effectively this would make the pinning something like `curl >=7.59,<8` (`7.59` is latest in c-f), right? This should resolve issue ( https://github.com/conda-forge/cmake-feedstock/issues/53 ) then.

cc @stuarteberg

**Comment by isuruf** [comment]
Yes.

**Comment by isuruf** [comment]
There are more packages like `fontconfig, bzip2, ffmpeg` that should be fixed.

**Comment by jakirkham** [comment]
`bzip2` is probably not worth thinking about too hard. There haven't been releases of it in almost a decade.

Agree with the others that we can relax them a bit.

**Comment by jakirkham** [comment]
Also `libpng` and `libtiff`.

ref: https://abi-laboratory.pro/tracker/timeline/libpng/
ref: https://abi-laboratory.pro/tracker/timeline/libtiff/

**Comment by jakirkham** [comment]
Took the liberty of renaming the issue to be a bit more general as I had trouble finding it. Hope that is ok. Feel free to tweak it further as needed.
