### ISSUE TITLE
Pinning x264

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-pinning-feedstock#51]
Appears that the history of `x264` includes annual SONAME changes and a fair bit of breakage. Would be good to work out some sensible pinning of `x264`. This will impact `ffmpeg`.

Independently the API/ABI tracker is lagging a bit. Have asked that it be updated in issue ( https://github.com/lvc/upstream-tracker/issues/43 ).

ref: https://abi-laboratory.pro/tracker/timeline/x264/

cc @conda-forge/x264 @conda-forge/ffmpeg

**Comment by jakirkham** [comment]
Could you please advise how one pins a version like this (given it is date-based and has no `.`s), @msarahan?

**Comment by carlodri** [comment]
@jakirkham maybe I'm naive but why is this a problem? A version with the <yyyy><mm><dd> format is a monotonically increasing number: isn't this enough to pin it?

**Comment by jakirkham** [comment]
One question is, how tightly do we want to pin it? The other question is, as the format is not typical (does not have `.`s) do things like `xxxx` work as expected (e.g. pinning the year)?

ref: https://conda.io/docs/user-guide/tasks/build-packages/variants.html#pinning-expressions

**Comment by carlodri** [comment]
yes, I get your point.

we could as well do something like 20180419 -> 2018.04.29 in the recipe, which IIUC would give us a version that compies with [PEP 440](https://www.python.org/dev/peps/pep-0440/) just like conda build. Dirty hack though IMO, would use only if really needed...

**Comment by carlodri** [comment]
as a first, simple start, we could use 20180429 as a major version number and use only that for pinning. PEP 440 allows single integers as version numbers.

**Comment by jakirkham** [comment]
@msarahan, could you please give us some advice here?

**Comment by msarahan** [comment]
If it is annual, maybe something like

dd.mm.YYYY

conda-build only increments things.  So it has no idea how to deal with composite data types like this that are run together.  Failing that, anything else would be manually defining the next bounds.

**Comment by jakirkham** [comment]
Part of the issue is it has no `.`s. So it goes `YYYYMMDD`. The concern would be if it tries to insert `.`s if we did something like `2018`. Does that make sense? Maybe that concern is unfounded and/or there are solutions in `conda-build` that we are unaware of.

**Comment by 183amir** [comment]
@jakirkham I think you are forgetting that you don't have to use `pin_subpackage` necessarily to get the `run_exports` behavior. Instead, x264 can have its own custom pinning in its recipe. Something like:
```yaml
{% set year = '2018' %}
{% set version = year + '0501' %}
{% set next_year = str(int(year) + 1) %}
...
  run_exports:
    - x264 >={{ version }},<{{ next_year }}0000
```
For example, see:
```sh
$ conda search -c anjos --override-channels x264                                  
Loading channels: ...working... done
# Name                  Version           Build  Channel             
x264                   20131217               3  anjos               
x264                   20170708      h0a2dd4e_1  anjos
$ conda search -c anjos --override-channels "x264[version='>=20131217,<20140000']"
Loading channels: ...working... done
# Name                  Version           Build  Channel             
x264                   20131217               3  anjos               
```

**Comment by sdvillal** [comment]
x264 has been updated, bringing a new .so version and breaking downstream dependencies (ffmpeg). See https://github.com/conda-forge/x264-feedstock/issues/16, https://github.com/conda-forge/ffmpeg-feedstock/issues/49 and a temporary solution (https://github.com/conda-forge/ffmpeg-feedstock/pull/48) that strictly pins x264 to the version used at build time.

How do we add a pin-x264 hotfix to old versions of ffmpeg? Is creating a new branch in the ffmpeg-feedstock per version we want to fix the best way?

**Comment by carlodri** [comment]
just to let you all know, I'm working on a PR on the `x264` feedstock based on @183amir's nice suggestion

**Comment by sdvillal** [comment]
Is pinning x264 to something on the lines ```>=2018xxxx,<2019xxxx```, as in @carlodri PR, the best we can do?

We are still relying on libx264 not changing the version/soname during 2018 (in which case we will have troubles again, that it has not happened in the past according to the ABI laboratory might just be anecdotal) and is too strict if the library gets updated but the soname does not change during 2019 (which definitely has happened in the past). I do not know what the libx264 policy is here. But I do not think we even need to bother and what we should do is to version based on the soname. As many linux distros do, for example:

https://packages.ubuntu.com/search?keywords=x264
https://www.archlinux.org/packages/extra/x86_64/x264/

Following that line would free us from trying to guess a good date-based pin spec.

So what about a version like "152.20180701" and pinning like ```152.*```?

**Comment by sdvillal** [comment]
New x264 package version strings look like ```1!so_number.YYYYMMDD```. Any pinning should use at least epoch and major (so_number) version, and hopefully use a loose date .
