### ISSUE TITLE
Migration to clang_osx64 17

### ISSUE THREAD

**Issue by anutosh491** [conda-forge/conda-forge-pinning-feedstock#5290]
### Comment:

I am opening this issue to track the migration for `clang_osx64` from version 16 to 17 here https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/4b0a1e27f055f3d6a9994a056751bbb06f50a535/recipe/conda_build_config.yaml#L17

After PR https://github.com/conda-forge/clang-compiler-activation-feedstock/pull/113 was merged I think version 17 can now be supported.

**Comment by h-vetinari** [comment]
This was done in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4890. We're even on clang [18](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6571) now! :)
