### ISSUE TITLE
Pinning nspr

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-pinning-feedstock#53]
Raising this to see how we would like to pin `nspr`. Here's the [ABI/API Report]( https://abi-laboratory.pro/tracker/timeline/nspr/ ), which looks pretty stable. The one removed symbol was from 4.17 to 4.18, which appears to be noted in the symbol name as being transient. We also skipped it. So maybe no pinning outside major version is needed? Not sure if there is anything else we should be doing here.

cc @conda-forge/nspr

**Comment by dougalsutherland** [comment]
Yeah, looks like major pinning only should be fine to me.

**Comment by jakirkham** [comment]
Fixing with PR ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/167 ).
