### ISSUE TITLE
Dropping CUDA 11.2

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/conda-forge-pinning-feedstock#5339]
Am raising this issue to discuss dropping CUDA 11.2

At this stage the bulk of conda-forge CUDA packages are built on CUDA 11.8, which supports the same hardware. Also CSPs have largely moved to CUDA 11.8+

The CUDA 11.2 Docker images that we use are [planned for deletion in May 2024]( https://gitlab.com/nvidia/container-images/cuda/-/issues/209#note_1641845842 ); whereas, the CUDA 11.8 Docker images remain available

Beginning with CUDA 12.0, standard conda-forge Docker images are used and the full CUDA Toolkit is made available with Conda packages

Given this, would propose dropping CUDA 11.2 and moving to CUDA 11.8 as the new minimum in conda-forge

Please let me know what you think

**Comment by jakirkham** [comment]
cc @conda-forge/core

**Comment by hmaarrfk** [comment]
I still have trouble personally running tendorflow with 11.8.

**Comment by jakirkham** [comment]
Saw some things over the holidays about that, but haven't quite caught up. Is there a particular place I should start reading?

In any event this isn't an immediate thing, but beginning May 2024 maintaining CUDA 11.2 will become untenable (as the NVIDIA Docker images will be deleted)

So let's start figuring out what we need to do to sunset 11.2. Right now I have...

* TensorFlow CUDA 11.8 issues (link?)

Anything else?

**Comment by hmaarrfk** [comment]
i see, i didn't know 11.2 was so old lol.

**Comment by h-vetinari** [comment]
IMO we have to finish the CUDA 11.8 migration first, by which I don't mean #5340, but fixing & merging the open 11.8 PRs (or at least greatly reduce them).

> In any event this isn't an immediate thing, but beginning May 2024 maintaining CUDA 11.2 will become untenable (as the NVIDIA Docker images will be deleted)

Our existing images won't be deleted. It'll just mean we cannot rebuild them. Granted, that's a bad place to be, but it's not like everything would break from one day to the next in May.

**Comment by jakirkham** [comment]
> IMO we have to finish the CUDA 11.8 migration first, by which I don't mean #5340, but fixing & merging the open 11.8 PRs (or at least greatly reduce them).

Had asked about what was still needed before closing out the migration [last meeting]( https://conda-forge.org/docs/orga/minutes/2023-12-13.html ). Didn't hear anything at that time. So we agreed to close it out

Both before and after that meeting spent substantial time with maintainers working to close out CUDA 11.8 PRs. The remaining feedstocks (with very few exceptions) are backlogged with multiple migration PRs and version updates. Given this, think we have likely already reach that state

That said, am happy to continue following up with maintainers who have questions on how to upgrade

> Our existing images won't be deleted. It'll just mean we cannot rebuild them. Granted, that's a bad place to be, but it's not like everything would break from one day to the next in May.

As noted before when this was brought up, if the community takes this route, the community will need to pick up maintenance around CUDA 11.2

Would just add this as food for thought, it seems like we are stretched thin of late. There are significant asks of our time around using newer GLIBC, macOS minimum, NumPy 2, proposed recipe format changes, etc.. Not to mention the day-to-day work of keeping things moving smoothly. Continuing to support the long tail doesn't seem like a realistic goal

**Comment by jaimergp** [comment]
Do we have a list of feedstocks stuck in 11.2? I think it's fair to move on to 11.8 by May if we communicate the timelines with them. Like "Hey 11.2 won't be supported after May, we want to make sure you are equipped to handle the transition or, otherwise, let us know how we can help".

**Comment by jakirkham** [comment]
For clarity the way we built for CUDA 11.2 was to restrict to 11.2 at build time and then allow [any CUDA 11.2+ at runtime]( https://github.com/conda-forge/nvcc-feedstock/blob/c01599568a71b44a3026970d6b5666f9c7e0e8be/recipe/meta.yaml#L45 ). So CUDA 11.8 installs are permissible with existing packages built for CUDA 11.2. IOW from an end user perspective installing packages, they would still be able to install old packages on CUDA 11.8

That said, we did run a CUDA 11.8 migrator ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/4834 ) and that ran for ~4 months until we closed it ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5340 ). During that time I did a lot of hand holding of maintainers to update feedstocks

By the time we closed the migration, 83% of feedstocks were migrated. Another 13% had an open CUDA 11.8 PR. Here's a [quick search result list of those]( https://github.com/search?q=org%3Aconda-forge+is%3Apr+is%3Aopen+%22Rebuild+for+CUDA+11.8%22&type=pullrequests&state=open ). This accounted for 96% of feedstocks. Another 4% had no PR (IIRC this was maybe 4-5). This info use to be under [the closed CUDA 11.8 migrator]( https://conda-forge.org/status/#cuda118 ), but I don't see it any more (maybe @beckermr can advise on how to regenerate that info)

If we think it is reasonable and are looking for an announcement, am happy to draft one so it will show up [on our new announcement page]( https://conda-forge.org/news/ ) 😉

**Comment by jakirkham** [comment]
Brought this up in the conda-forge meeting today, sounds like there are no objections to dropping

Next step will be adding an announcement that this will be dropped

Recommendation is to pick first day of work week before the Docker image is deleted so that folks have time to do any remediation

**Comment by jakirkham** [comment]
> Do we have a list of feedstocks stuck in 11.2? I think it's fair to move on to 11.8 by May if we communicate the timelines with them. Like "Hey 11.2 won't be supported after May, we want to make sure you are equipped to handle the transition or, otherwise, let us know how we can help".

After doing a bit of digging, was able to identify when the CUDA 11.8 migration data was removed from the bot (so the last migration status):

```
$ git log --all -1 -- status/migration_json/cuda118.json                                      
commit eb8d2a43d20f9de828ace2c17036544e49b4546d
Author: regro-cf-autotick-bot <36490558+regro-cf-autotick-bot@users.noreply.github.com>
Date:   Thu Jan 25 21:58:24 2024 +0000

    Update Graph https://github.com/regro/cf-scripts/actions/runs/7660837918
```

It appears the bot removed the CUDA 11.8 migration data in commit ( https://github.com/regro/cf-graph-countyfair/commit/eb8d2a43d20f9de828ace2c17036544e49b4546d ). Looking at the CUDA 11.8 migration status before that can find [a handful of feedstocks without PRs]( https://github.com/regro/cf-graph-countyfair/blob/adcfa00d0f1b9430ad812ca8cec1286fd8601576/status/migration_json/cuda118.json#L910-L918 ). Based on that opened the following issues:

* https://github.com/conda-forge/tsnecuda-feedstock/issues/9
* https://github.com/conda-forge/graphvite-feedstock/issues/5
* https://github.com/conda-forge/tvm-py-feedstock/issues/31
* https://github.com/conda-forge/timemory-feedstock/issues/19

That said, according to GitHub the last commit to `main` for all of these was 2 years ago. So think it is unlikely they are updated any time soon

**Comment by jakirkham** [comment]
> Next step will be adding an announcement that this will be dropped

Have submitted an announcement in PR: https://github.com/conda-forge/conda-forge.github.io/pull/2098

**Comment by jakirkham** [comment]
Also found these CUDA 11.8 migration PRs, which are still open

* conda-forge/cudadecon-feedstock#26
* conda-forge/fairscale-feedstock#31
* conda-forge/faiss-split-feedstock#70
* conda-forge/heavydb-ext-feedstock#67
* conda-forge/kaolin-feedstock#19
* conda-forge/meld-feedstock#22
* conda-forge/rmm-feedstock#27
* conda-forge/torch-scatter-feedstock#26
* conda-forge/torchsparse-feedstock#27
* conda-forge/xformers-feedstock#15

In many cases they have other open migrations and version updates

Re-rendered and merged their contents into the CUDA 12 migrators that they all have open. So these can be resolved with the CUDA 12 migrations

As CUDA 11.8 is already in the CUDA build matrix, simply re-rendering any PR would add CUDA 11.8 (unless explicitly skipped in the recipe)

**Comment by jakirkham** [comment]
>> Next step will be adding an announcement that this will be dropped
>
> Have submitted an announcement in PR: https://github.com/conda-forge/conda-forge.github.io/pull/2098

The announcement is now live: https://conda-forge.org/news/2024/03/06/dropping-cuda-112/

**Comment by jakirkham** [comment]
@h-vetinari just dropped CUDA 11.2 and bumped the minimum to CUDA 11.8 in PR: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5799

Dropping CUDA 11.2 from `staged-recipes` with PR: https://github.com/conda-forge/staged-recipes/pull/26204

Also as the CUDA minimum in conda-forge is now 11.8, dropping all CUDA images pre-11.8 in PR: https://github.com/conda-forge/docker-images/pull/262

**Comment by jakirkham** [comment]
This is now complete. Closing this out

Thanks all! 🙏
