### ISSUE TITLE
CUDA 12 version in cbc.yaml - plans?

### ISSUE THREAD

**Issue by danpetry** [conda-forge/conda-forge-pinning-feedstock#5390]
### Comment:

Just wondering what the plans/current thinking is for including cuda v12 here? Has there been a buildout discussed?

**Comment by jakirkham** [comment]
The usual process when making updates to the global pinnings is

1. Add a migrator
2. Update feedstocks with the migrator via the bot (potentially with some manual intervention)
3. Close out the migrator (once it is sufficiently complete, which can be somewhat subjective)

After 3, the global pinnings are updated

More information in [these docs]( https://conda-forge.org/docs/maintainer/knowledge_base.html#migrators-and-migrations )

<hr>

Currently there is a CUDA 12 conda-forge migration occurring, which is being handled with [this migrator]( https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/9a71994addee3be05dc14e758e00b9b2617f9de3/recipe/migrations/cuda120.yaml ). Also here is [the current status of the CUDA 12 migrator]( https://conda-forge.org/status/#cuda120 ). It is ~68% complete at the time of this writing

As the CUDA 12 migration has involved more changes that the average migration, there is a detailed write up of the changes involved and the reasons for them in issue ( https://github.com/conda-forge/conda-forge.github.io/issues/1963 ). This provides more guidance on how feedstocks can build with CUDA 12 packages

**Comment by jakirkham** [comment]
Thanks to @h-vetinari recent comment ( https://github.com/conda-forge/conda-forge.github.io/issues/1963#issuecomment-1985134794 ) was looking again at the CUDA 12 migrator status. Here are some observations:

* 95% are either migrated or already have a migration PR
  * 75% have CUDA 12 packages
  * 20% have an open PR
* 5% have not gotten a PR
  * 3% are waiting for parents to be rebuilt
  * 2% the bot errored trying to make a PR

Based on this, would agree the migration has reached its natural conclusion

Given this would recommend we close out the migration. Have added this in PR: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5613

Also to make sure that newly added packages build with CUDA 12 successfully (given the new package structure), have submitted PR: https://github.com/conda-forge/staged-recipes/pull/25675

**Comment by jakirkham** [comment]
cc @conda-forge/core

**Comment by hmaarrfk** [comment]
I agree. Let’s close it
