### ISSUE TITLE
Fix Wiki?

### ISSUE THREAD

**Issue by kyleabeauchamp** [conda-forge/conda-forge-pinning-feedstock#54]
In several places I've seen a link to the following wiki:

https://github.com/conda-forge/staged-recipes/wiki/Pinned-dependencies

But every time I go there it's empty.  Is this a deprecated wiki page or a page that's waiting to be built?

**Comment by jakirkham** [comment]
> But every time I go there it's empty. Is this a deprecated wiki page or a page that's waiting to be built?

Yes, it is deprecated. Here are the [current docs]( https://conda-forge.org/docs/meta.html#pinning-packages ). The specific pinnings live in [this file]( https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml ). For the most part, explicitly pinning dependencies should not be needed as `conda-smithy` 3+ handles this for you as part of re-rendering.
