### ISSUE TITLE
Migration libprotobuf4251 not being performed for abi_migration_branches ?

### ISSUE THREAD

**Issue by traversaro** [conda-forge/conda-forge-pinning-feedstock#5435]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

During libprotobuf4251  migration, we noticed that for some reason the migration is not performed for non-main branches specified in `abi_migration_branches` . 

For example, see how the `tinyxml210` migration opened two PRs in the following repos:

* https://github.com/conda-forge/libignition-msgs1-feedstock/pull/99
* https://github.com/conda-forge/libignition-msgs1-feedstock/pull/100
* https://github.com/conda-forge/libignition-fuel-tools-feedstock/pull/82
* https://github.com/conda-forge/libignition-fuel-tools-feedstock/pull/81

However, in the same repos the `libprotobuf4251` migration opened only a single PR:

* https://github.com/conda-forge/libignition-msgs1-feedstock/pull/101
* https://github.com/conda-forge/libignition-fuel-tools-feedstock/pull/83

This eventually resulted in a migration failure in a leaf feedstock that depends on older version of the dependency:
* https://github.com/conda-forge/gazebo-feedstock/pull/201

I would investigate the issue myself but I am a bit out of pointers or clues of where to start.

I am not sure if this is the right place where to open this issue, but to avoid decision paralysis I just opened it somewhere, feel free to redirect it, thanks!

fyi @conda-forge/libprotobuf 

### Installed packages

```shell
.
```

### Environment info

```shell
.
```

**Comment by traversaro** [comment]
Note that I can unblock the situation in this specific case with manual migrations, but I preferred to open an issue to report the problem.

**Comment by h-vetinari** [comment]
The status page does not report what's happening on ABI branches separately, but historically the non-main PRs were opened _even if_ there were missing dependencies.

I also noticed this on a couple other protobuf-dependent feedstocks with branches (e.g. singlejar).

No idea what could be causing it.

CC @beckermr

**Comment by beckermr** [comment]
We likely need to inspect the bot logs to figure this out.

**Comment by beckermr** [comment]
@traversaro Can you make this issue on regro/cf-scripts?

**Comment by traversaro** [comment]
> @traversaro Can you make this issue on regro/cf-scripts?

Sure, done in https://github.com/regro/cf-scripts/issues/2126 .

**Comment by traversaro** [comment]
I think we can close this now.
