### ISSUE TITLE
adding libparallelproj to conda-forge-pinning-feedstock

### ISSUE THREAD

**Issue by gschramm** [conda-forge/conda-forge-pinning-feedstock#5447]
### Comment:

`libparallelproj` which is part of the conda-forge package [parallelproj](https://github.com/conda-forge/parallelproj-feedstock) contains C/CUDA libs consumed / linked by other projects - e.g. [STIR](https://github.com/conda-forge/stir-feedstock/blob/5a79f83baac5fe148a1be37cf63fd17a8b606823/recipe/meta.yaml#L47) (also on conda-forge). 

Recently, the maintainer of STIR and the STIR conda-forge feedstock reported [this issue](https://github.com/conda-forge/stir-feedstock/issues/106#issuecomment-1917269011) occurring at the loading stage of `libparallelproj` caused by different versions used for building and when installing.

Because of that, I assume `libparallelproj` is a candidate to be added to conda-forge-pinning? 
Or should the pinning be done manually in the STIR recipe?
Or do I need to define a `run_export` in the parallelproj recipe?

I am using semantic versioning for `libparallelproj`, so in principle STIR built with `libparallelproj` v1.7.1 should run with v1.7.3 - so I am also a bit lost on why there is a problem in the loading stage

**Comment by xhochy** [comment]
You should be:

1. Define a `run_exports` in `libparallelproj`
2. Add a migration to this repository and add the same version to the `conda_build_config.yaml`
3. Add a repodata patch for the old STIR builds so that they depend on the correct `libparallelproj`.

**Comment by gschramm** [comment]
@xhochy : thanks a lot for the feedback!

I am struggling to understand how the `run_exports` work / what they mean (after reading the.
Right now, we already have `run_exports` in the recipe of `libparallelproj` - see [here](https://github.com/conda-forge/parallelproj-feedstock/blob/af5ce4eec004af3b009b74156843194858741cbe/recipe/meta.yaml#L26), but I guess
they are not correct.

What we need is that respects semantic versioning meaning that an application build with `libparallelproj vX.Y` should run with all `libparallelproj X.>=Y` versions (and choosing the correct cpu vs cuda build)

**Comment by xhochy** [comment]
> What we need is that respects semantic versioning meaning that an application build with libparallelproj vX.Y should run with all libparallelproj X.>=Y versions (and choosing the correct cpu vs cuda build)

Yes, this means you are missing a `max_pin='x.x'` in the `pin_subpackage` call.

**Comment by gschramm** [comment]
Could you also explain what:
"Add a migration to this repository and add the same version to the conda_build_config.yaml"
means and does?

**Comment by xhochy** [comment]
For a migration, you can see the following PR as an example: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5824/files  It will take care that all repositories that depend on a package are rebuilt in topological order with the package pinned to the same versions.

**Comment by gschramm** [comment]
Many thanks again! So if I understand correctly, I will submit a PR containing
```
__migrator:
  build_number: 1
  commit_message: Rebuild for libparallelproj 1.8.0
  kind: version
  migration_number: 1
migrator_ts: "time stamp"
libparallelproj:
- 1.8.0
```
and the time stamp is the time stamp of the submission?

**Comment by xhochy** [comment]
Yes, in the example migration file there is a bit more documentation.

**Comment by xhochy** [comment]
No, this needs to be the package that should be pinned, not the feedstock.

**Comment by gschramm** [comment]
Ah ok. Good that I double checked.
I think the comment in the example migration file [here](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/a86a9a1a53977b29e29f4c95d7c8cb72e0f02c93/recipe/migrations/example.exyaml#L17) is a bit misleading

**Comment by gschramm** [comment]
@KrisThielemans : Does the issue still exist?
The PR to the pinning feedstock was merged in April: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5825
And the `max_pin=x.x` in `pin_subpackage` is also included in the libparallelproj feedstock recipe:
https://github.com/conda-forge/parallelproj-feedstock/blob/5467feb05a209d89b5cacbd635a5ff7ffc5190eb/recipe/meta.yaml#L26

**Comment by KrisThielemans** [comment]
ah ok. I couldn't (can't) find any mention of libparallelproj in this feedstock though, but have no idea how this works.

If everything is done, then this issue should be closed I suppose 😄 

(I didn't actually have any problems, but just wondered what the status was)

**Comment by gschramm** [comment]
@KrisThielemans Let me know if people report problems
