### ISSUE TITLE
add pre-commit CI to make sure yaml is valid

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge-pinning-feedstock#5562]
Duplicate keys in the migrators is breaking stuff. We should add pre-commit or something to ensure we have valid yaml.

**Comment by beckermr** [comment]
cc @chrisburr @jakirkham

**Comment by jakirkham** [comment]
Can you please share more context? What is breaking where?

**Comment by beckermr** [comment]
We had duplicate keys in some of the migrator yaml files and this breaks everything.

**Comment by beckermr** [comment]
Everything being all of the bot.

**Comment by beckermr** [comment]
It's also not properly defined and is a bug.

**Comment by jakirkham** [comment]
Which keys? Is there a log? Sorry am trying to help, but I need more info to go on

**Comment by beckermr** [comment]
See the latest root base migrator and the fix I made to it.

**Comment by jakirkham** [comment]
> See the latest root base migrator and the fix I made to it.

Linking for posterity: https://github.com/conda-forge/conda-forge-pinning-feedstock/commit/e578e46ce17da1dc490ce16109ed632978c8a543
