### ISSUE TITLE
numpy2.0 migration PRs have numpy1 .26 for python 3.12

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge-pinning-feedstock#5843]
When I was testing the numpy2 migration on pandas, I noticed with the latest pinnings that python 3.12 was getting numpy 1.26 and not 2.0. Is this intended?

cc @h-vetinari @hmaarrfk @jakirkham @conda-forge/core

**Comment by h-vetinari** [comment]
See this [comment](https://github.com/conda-forge/conda-forge.github.io/issues/1997#issuecomment-2094361188). If you have a solution, even better!

**Comment by beckermr** [comment]
Ahhhhh I missed that. Makes sense but is unfortunate. We could just close the python 3.12 migration?

Happy to leave this for now too.
