### ISSUE TITLE
Close Python 3.12 migration

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-forge-pinning-feedstock#5892]
In the context of #5851, we need to either close the python 3.12 migration or accept up to 2k potentially redundant PRs, due to various issues around zips and otherwise not being able to migrate numpy 2 for python 3.12 if it's still in a migrator.

So the suggestion was floated to close the 3.12 migration, and I went through all open PRs (that have >1 children) and tried to at least diagnose, and ideally fix/merge them. As of now, we have

![image](https://github.com/conda-forge/conda-forge-pinning-feedstock/assets/33685575/e14e96cb-a587-4180-bf0b-4abef2f2b290)

The last big blocker is tensorflow, for which I have a [PR](https://github.com/conda-forge/tensorflow-feedstock/pull/385) that's nearly done. I've tried spacy, but it's not yet compatible with 3.12 (AFAICT due to using tracing, which Cython 3.0 doesn't support for 3.12 yet). The remaining packages with a moderate number of children aren't compatible yet either, or fail due to unrelated reasons:
* https://github.com/conda-forge/pyfftw-feedstock/pull/61
* https://github.com/conda-forge/root-feedstock/pull/237
* https://github.com/conda-forge/pyside2-feedstock/pull/199
* https://github.com/conda-forge/awscli2-feedstock/pull/39

The percentage number at the top is a bit misleading - it reports the percentage of "PRs opened", not "PRs closed". So we're actually at ~70% with the 3.12 migration, with about ~850 feedstocks still to go. In the past years, we've mostly closed the 3.X migration once we started migrating for 3.{X+1}, but OTOH, the activity here has died down almost completely, so given the numpy 2 situation, I think this is actually worth considering.

**Comment by hmaarrfk** [comment]
I think the packages depending on pyside2 should likely consider moving to pyside6 in 2024. 

Given the status, i'm in favor of closing, users can add `skip: true  # [py>311]` if things are failing

Is it possible to "soft close" it? I find the `status` page useful to better understand what still needs to happen if anybody has questions.

**Comment by h-vetinari** [comment]
> Is it possible to "soft close" it? I find the `status` page useful to better understand what still needs to happen if anybody has questions.

Yeah, good idea! 👍

That should work, at least in the sense that we'd still continue having the migrator on the status page, and PRs issued whenever an affected feedstock (with all required dependencies from the POV of the migrator) doesn't have `python312.yaml` yet.

**Comment by hmaarrfk** [comment]
i'm just not sure how "softclosing" works when we add a zip key. if it is any added maintenance, we should just close IMO

**Comment by h-vetinari** [comment]
> i'm just not sure how "softclosing" works when we add a zip key. if it is any added maintenance, we should just close IMO

It works. :)
