### ISSUE TITLE
Pinning suitesparse

### ISSUE THREAD

**Issue by martinandersen** [conda-forge/conda-forge-pinning-feedstock#59]
Raising this to see if suitesparse should be pinned globally. 

re conda-forge/cvxopt-feedstock#19

**Comment by dougalsutherland** [comment]
For the record, it's only broken compatibility on major versions, so the CB3 default behavior if you just list `- suitesparse` in `run` should be okay: https://abi-laboratory.pro/tracker/timeline/suitesparse/. But I guess there was an issue with the Mac `install_name` (https://github.com/conda-forge/cvxopt-feedstock/pull/19#discussion_r187432021)?

**Comment by jakirkham** [comment]
cc @minrk
