### ISSUE TITLE
Migration not running for qt6_main

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/conda-forge-pinning-feedstock#5906]
### Comment:

Is there something wrong with the generated file:
https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/5780

**Comment by beckermr** [comment]
Did you check the main branch? Something deleted that file.

**Comment by hmaarrfk** [comment]
hmm ok, lets monitor in the future. i know that the migrators were getting stuck a few times and many qt6 projects have strange syntax in their meta.yaml

**Comment by beckermr** [comment]
We should double check that the migrator itself was formatted correctly. The bot may not have properly generated the graph.

**Comment by hmaarrfk** [comment]
Yeah. That could be it too. There should be an update every few months. Let’s see what happens. 

Many packages are moving to qt6 only these days.
