### ISSUE TITLE
Convert `{{ posix }}pkg-config` to `pkg-config` in UCRT migrator

### ISSUE THREAD

**Issue by mfansler** [conda-forge/conda-forge-pinning-feedstock#6180]
Todo from R migration...

              This change should be in the mini migrator

_Originally posted by @isuruf in https://github.com/conda-forge/r-httpuv-feedstock/pull/43#discussion_r1676963561_

**Comment by isuruf** [comment]
Can you open this at regro/cf-scripts ?

**Comment by mfansler** [comment]
No problem - now over here: https://github.com/regro/cf-scripts/issues/2847
