### ISSUE TITLE
Use alma9 images on linux, while staying on 2.17 sysroot

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-forge-pinning-feedstock#6283]
Since it's taken us so long to upgrade from centOS 6 to 7, we'll very quickly find ourselves in a situation that we struggled with already some time ago (see discussion in this [issue](https://github.com/conda-forge/conda-forge.github.io/issues/1436)): a growing number of feedstocks will require a newer glibc, and our images should provide a new enough baseline version, so that the only thing that feedstocks need to actively override is `c_stdlib_version` (and thus the sysroot), but nothing else.

For example, google's "foundational" support matrix [defines](https://github.com/google/oss-policies-info/blob/0c6d8dfaf4bb48ec2505c79b9825b4986e1f1ebe/foundational-cxx-support-matrix.md?plain=1#L24) a lower bound of glibc 2.27, meaning that things like abseil/bazel/grpc/protobuf/re2 etc. will start beginning to rely on glibc features >2.17 in the near future (and even though it's not a google project, one of the baseline dependencies of that stack is [starting](https://github.com/conda-forge/c-ares-feedstock/pull/38) to require it).

We can handle the `c_stdlib_version` in the migrators (like we [did](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/a9c6bf9af2f75c46aaeeda445c87cec43970aeb4/recipe/migrations/libabseil20230802_libgrpc157_libprotobuf4234.yaml#L1-L10) for macOS 10.13, before the conda-forge-wide baseline was lifted), but changing more than one key of the mega-zip involving the docker images is really painful, especially if CUDA is involved ([example](https://github.com/conda-forge/faiss-split-feedstock/blob/a329d1efab47efb466050dbaea52b5d26876649d/recipe/conda_build_config.yaml#L1-L35)), so having the images be alma8 by default will be very helpful there.

To a lesser extent, it will also save us from run-time bugs in older glibc versions, like we had with some broken trigonometry functions in 2.12 (before the image moved to cos7 while the sysroot still stayed at 2.12).

There are other scenarios still where this is necessary, see the discussion [here](https://github.com/conda-forge/conda-forge.github.io/pull/2206#discussion_r1674100297) for example.

While it's already possible to use alma8 images, the main thing we're blocked is the lack of CDTs for alma 8 (pending https://github.com/conda-forge/cdt-builds/issues/66), c.f. https://github.com/conda-forge/conda-forge.github.io/issues/1941

This issue is for tracking this effort, and any other eventual tasks that need to be resolved before doing so.

**Comment by hmaarrfk** [comment]
It would be great if we could do this for aarch + cuda12 to start. But I think we should generally move the base image forward.

xref: https://github.com/conda-forge/pytorch-cpu-feedstock/blob/main/recipe/conda_build_config.yaml#L17

**Comment by h-vetinari** [comment]
AFAIU the only remaining issue is the reduction of CDTs from cos7 to alma8; we should try to do a special "remove/replace CDTs" migration because breaking 100+ feedstocks is not really a good option, even if we provide a way to opt into the old images again.

**Comment by hmaarrfk** [comment]
Ah i see, the tk feedstock throws quite a thorn in the "rip out all the CDTs too".

**Comment by isuruf** [comment]
Using alma8 images and using an up-to-date sysroot are two different problems. In order to change to alma8 images, we just need to check to see if all the requirements in `recipe/yum_requirements.txt` are available in the alma8 images.

**Comment by isuruf** [comment]
It doesn't have to be an exhaustive check, but just a few feedstocks that use yum requirements to see if it really works.

**Comment by jakirkham** [comment]
Wonder if a smaller step would simply making it a bit easier for users to opt-in to using the newer images

Did a little exploration of this in PR: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6548

Likely needs more work, but maybe it is already useful for discussion/iteration at this stage

**Comment by h-vetinari** [comment]
> In order to change to alma8 images, we just need to check to see if all the requirements in `recipe/yum_requirements.txt` are available in the alma8 images.

So I took the content of [all](https://github.com/search?q=org%3Aconda-forge+path%3Arecipe%2Fyum_requirements.txt&type=code) the `yum_requirements.txt` in conda-forge. Many of them can be replaced (x11, mesa, alsa, various tool that we have packaged).

| entries from<br/>`yum_reqirements.txt` | is it still<br/>necessary? | available<br/>on alma8? | comment |
|-|-|-|-|
| alsa-lib | ❌ | ✅ | use our `alsa-lib` |
| alsa-lib-devel | ❌ | ✅ | use our `alsa-lib` |
| alsa-tools | ❔ | ❌ | |
| binutils | ✅ | ✅ | used only for our [`binutils`](https://github.com/conda-forge/binutils-feedstock) |
| csh | ❔ | ❌ | there's `tcsh` in [centos7](https://vault.centos.org/7.9.2009/os/x86_64/Packages/)/[alma8](https://pkgs.org/search/?q=csh), but I cannot find `csh` in either |
| chrpath | ❌ | ✅ | used only on obsolete [`qt`](https://github.com/conda-forge/qt-feedstock) feedstock |
| dbus-devel | ❔ | ✅ | |
| dbus-libs | ❔ | ✅ | |
| dejavu-sans-mono-fonts | ❔ | ✅ | used only for [`pymor`](https://github.com/conda-forge/pymor-feedstock) |
| ed | ❔ | ✅ | used only for [`bc`](https://github.com/conda-forge/bc-feedstock) |
| file | ✅ | ✅ | used to bootstrap [`crosstool-ng`](https://github.com/conda-forge/crosstool-ng-feedstock) |
| findutils | ✅ | ✅ | used to bootstrap [linux compilers](https://github.com/conda-forge/ctng-compilers-feedstock) and [`crosstool-ng`](https://github.com/conda-forge/crosstool-ng-feedstock) |
| gcc-c++ | ✅ | ✅ | used to bootstrap [linux compilers](https://github.com/conda-forge/ctng-compilers-feedstock) and [`binutils`](https://github.com/conda-forge/binutils-feedstock) |
| gcc-gfortran | ✅ | ✅ | used to bootstrap [linux compilers](https://github.com/conda-forge/ctng-compilers-feedstock) |
| gtk2 | ❌ | ✅ | use our [`gtk2`](https://github.com/conda-forge/gtk2-feedstock) |
| gtk2-devel | ❌ | ✅ | use our [`gtk2`](https://github.com/conda-forge/gtk2-feedstock) |
| gtk3 | ❌ | ✅ | use our [`gtk3`](https://github.com/conda-forge/gtk3-feedstock) |
| gtk3-devel | ❌ | ✅ | use our [`gtk3`](https://github.com/conda-forge/gtk3-feedstock) |
| gtkmm24 | ❔| ✅ | use our [`gtkmm`](https://github.com/conda-forge/gtkmm-feedstock)? |
| hatchling | ❌ | ❌ | cannot find it in either centos7/alma8;<br/>use our `hatchling`; only used for [`biosiglive`](https://github.com/conda-forge/biosiglive-feedstock) |
| help2man | ✅ | ✅ | used to bootstrap [linux compilers](https://github.com/conda-forge/ctng-compilers-feedstock) |
| httpd-devel | ❔ | ✅ | only used for [`mod_wsgi`](https://github.com/conda-forge/mod_wsgi-feedstock) |
| kernel-headers | ❌ | ✅ | use our `cdt("kernel-headers")`; only used for [`gdal`](https://github.com/conda-forge/gdal-feedstock) |
| libglu1-mesa | ❌ | ✅ | this is the Debian-style [naming](https://pkgs.org/download/libglu1); RHEL-style has `mesa-libGLU`;<br/>use our `libglvnd{,-devel}` |
| libglvnd-egl | ❌ | ✅ | use our `libglvnd{,-devel}` |
| libglvnd-glx | ❌ | ✅ | use our `libglvnd{,-devel}` |
| libglvnd-opengl | ❌ | ✅ | use our `libglvnd{,-devel}` |
| libice | ❌ | ✅ | use our `xorg-libice` |
| libice-devel | ❌ | ✅ | use our `xorg-libice` |
| libselinux | ✅ | ✅ | |
| libsm | ❌ | ✅ | use our `xorg-libsm` |
| libsm-devel | ❌ | ✅ | use our `xorg-libsm` |
| libudev | ❔ | ❌ | this is the Debian-style [naming](https://pkgs.org/search/?q=libudev); we also have our own [`libudev`](https://github.com/conda-forge/systemd-feedstock) |
| libudev-devel | ❔ | ❌ | this is the Debian-style [naming](https://pkgs.org/search/?q=libudev); we also have our own [`libudev`](https://github.com/conda-forge/systemd-feedstock) |
| libX11 | ✅ | ✅ | use our `xorg-libx11`, but needed on [`python`](https://github.com/conda-forge/python-feedstock) |
| libX11-devel | ❌ | ✅ | use our `xorg-libx11` |
| libXau / libxau | ✅ | ✅ | use our `xorg-libxau`, but needed on [`python`](https://github.com/conda-forge/python-feedstock) |
| libXau-devel | ❌ | ✅ | use our `xorg-libxau` |
| libxcb | ✅ | ✅ | use our `libxcb`, but needed on [`python`](https://github.com/conda-forge/python-feedstock) |
| libXcomposite | ❌ | ✅ | use our `xorg-libxcomposite` |
| libXcomposite-devel | ❌ | ✅ | use our `xorg-libxcomposite` |
| libXcursor | ❌ | ✅ | use our `xorg-libxcursor` |
| libXcursor-devel | ❌ | ✅ | use our `xorg-libxcursor` |
| libXdamage | ❌ | ✅ | use our `xorg-libxdamage` |
| libXdmcp | ❌ | ✅ | use our `xorg-libxdmcp` |
| libXdmcp-devel | ❌ | ✅ | use our `xorg-libxdmcp` |
| libXext | ❌ | ✅ | use our `xorg-libxext` |
| libXext-devel | ❌ | ✅ | use our `xorg-libxext` |
| libXfixes | ❌ | ✅ | use our `xorg-libxfixes` |
| libXi | ❌ | ✅ | use our `xorg-libxi` |
| libXi-devel | ❌ | ✅ | use our `xorg-libxi` |
| libXinerama | ❌ | ✅ | use our `xorg-libxinerama` |
| libxkbcommon-x11 | ❌ | ✅ | use our `libxkbcommon` |
| libXrandr | ❌ | ✅ | use our `xorg-libxrandr` |
| libXrandr-devel | ❌ | ✅ | use our `xorg-libxrandr` |
| libXrender | ❌ | ✅ | use our `xorg-libxrender` |
| libXrender-devel | ❌ | ✅ | use our `xorg-libxrender` |
| libXScrnSaver | ❌ | ✅ | use our `xorg-libxscrnsaver` |
| libXScrnSaver-devel | ❌ | ✅ | use our `xorg-libxscrnsaver` |
| libXt | ❌ | ✅ | use our `xorg-libxt` |
| libXt-devel | ❌ | ✅ | use our `xorg-libxt` |
| libXtst | ❌ | ✅ | use our `xorg-libxst` |
| libXtst-devel | ❌ | ✅ | use our `xorg-libxst` |
| libXxf86vm | ❌ | ✅ | use our `xorg-libxxf86vm` |
| m4 | ✅ | ✅ | used to bootstrap [linux compilers](https://github.com/conda-forge/ctng-compilers-feedstock) |
| make | ✅ | ❌ | there is `make-latest` / `make43`;<br/>used to our [`binutils`](https://github.com/conda-forge/binutils-feedstock) and other infra |
| mesa-dri-drivers | ❌ | ✅ | use our `libglvnd{,-devel}` |
| mesa-libEGL | ❌ | ✅ | use our `libglvnd{,-devel}` |
| mesa-libEGL-devel | ❌ | ✅ | use our `libglvnd{,-devel}` |
| mesa-libGL<br/>mesa-libgl | ❌ | ✅ | use our `libglvnd{,-devel}` |
| mesa-libGL-devel | ❌ | ✅ | use our `libglvnd{,-devel}` |
| mesa-libGLU | ❌ | ✅ | use our `libglvnd{,-devel}` |
| mesa-libGLU-devel | ❌ | ✅ | use our `libglvnd{,-devel}` |
| numactl | ❌ | ✅ | use our `numactl` |
| numactl-devel | ❌ | ✅ | use our `numactl` |
| patch | ✅ | ✅ | used to bootstrap [linux compilers](https://github.com/conda-forge/ctng-compilers-feedstock) |
| pciutils | ❔ | ✅ | |
| pciutils-devel | ❔ | ✅ | |
| pciutils-libs | ❔ | ✅ | |
| perl | ❌ | ✅ | use our `perl` |
| pulseaudio-libs-devel | ❌ | ✅ | use our `pulseaudio`; only used for [`pocketsphinx-python`](https://github.com/conda-forge/pocketsphinx-python-feedstock) |
| python-docutils | ❔ | ❌ | there's `python3-docutils`; but use our `docutils`;<br/>only used for [`rdma-core`](https://github.com/conda-forge/rdma-core-feedstock) |
| rsh | ❔ | ❌ | no idea what this is for |
| rsync | ✅ | ✅ | used to bootstrap [linux compilers](https://github.com/conda-forge/ctng-compilers-feedstock) |
| sed | ✅ | ✅ | used to bootstrap [linux compilers](https://github.com/conda-forge/ctng-compilers-feedstock) and [`crosstool-ng`](https://github.com/conda-forge/crosstool-ng-feedstock) |
| systemd-devel | ❔ | ✅ | we have our own [`libsystemd`](https://github.com/conda-forge/systemd-feedstock) |
| texinfo | ✅ | ✅ | used to bootstrap our [`binutils`](https://github.com/conda-forge/binutils-feedstock) |
| util-linux | ❌ | ✅ | use our `util-linux` |
| wget | ✅ | ✅ | used to bootstrap [linux compilers](https://github.com/conda-forge/ctng-compilers-feedstock) |
| xauth | ❌ | ❌ | doesn't exist on either centos7/alma8,<br/>but `xorg-x11-xauth` exists in both; but use our `xorg-xauth` |
| xorg-x11-server-Xorg | ❔ | ✅ | |
| xorg-x11-server-Xvfb | ❔ | ✅ | |

**Comment by jakirkham** [comment]
Thanks for pulling together this list Axel and going over it in today's call! 🙏

Cleaned up the `rdma-core` case. It also uses `systemd`

What do we think about making a migrator? At least with X11, this seems essential given that gets pulled in all over the place. Though this may extend to other places

**Comment by h-vetinari** [comment]
> What do we think about making a migrator?

My understanding was that a migrator is not necessary. The yum_requirements will continue to work, and if CDTs end up missing they can be replaced with our own deps, or alternatively users set `os_version: cos7` in their `conda-forge.yml`

**Comment by h-vetinari** [comment]
In the discussion in https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6548, @carterbox made the [point](https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/6548#issuecomment-2452776490) (IIUC) that we may want to simply use alma 9(!) images by default, even if we keep the sysroot at 2.17 (== cos7). The reason being (paraphrasing according to my interpretation) that it removes one mostly unnecessary dimension from the whole pinning exercise.

In principle I think this sounds like a good idea to me - the actual glibc in the image doesn't matter from the POV of building packages or any our metadata, it only needs to be _new enough_ to run anything we might want to throw at it at runtime. So if someone decides to use glibc 2.34 in the future, that would simply make the question about how to change the image version obsolete, because the containers would have a new enough version for everything we support to build.

The question becomes what if any failures are possible if the container image is too new. I suspect that this would be very rare (otherwise we would have been hitting such cases all the time when we used cos7 images to build cos6 stuff).

**Comment by carterbox** [comment]
This summarizes my point correctly. I am also curious if anyone can think of a case in which having a container that is too new would cause problems. Maybe this is something for the next core meeting.

**Comment by isuruf** [comment]
> I am also curious if anyone can think of a case in which having a container that is too new would cause problems.

Usually not. There are some rare cases. For eg:
1. binary re-packaging which is done by cuda-* feedstocks.
2. the build system might inspect the system to see if there are some bugs in older glibc to add workarounds.

**Comment by h-vetinari** [comment]
> > I am also curious if anyone can think of a case in which having a container that is too new would cause problems.
> 
> Usually not. There are some rare cases.

That matches my understanding too. And obviously those cases could still choose alma8 (or even cos7) images. We can also leave the `DEFAULT_LINUX_VERSION` infrastructure in place to facilitate that. But I think we're inching towards agreement that we could be using alma9 images by default. :)

> There aren't any meeting notes for the next meeting available yet.

Here you go: https://github.com/conda-forge/conda-forge.github.io/pull/2350

**Comment by traversaro** [comment]
> So I took the content of [all](https://github.com/search?q=org%3Aconda-forge+path%3Arecipe%2Fyum_requirements.txt&type=code) the `yum_requirements.txt` in conda-forge[1](#user-content-fn-1-69cd3697c8caf42b083e1214eae49b50). Many of them can be replaced (x11, mesa, alsa, various tool that we have packaged).

Minor comment: I do not think `mesa-dri-drivers` can be substituted with conda-forge's libglvnd-devel, as it contains the actual EGL/GLX drivers, while libglvnd-devel only contains the loader.

**Comment by h-vetinari** [comment]
> I do not think `mesa-dri-drivers` can be substituted with conda-forge's libglvnd-devel, as it contains the actual EGL/GLX drivers, while libglvnd-devel only contains the loader.

Yes, that's part of the compiletime-runtime split between CDTs and `yum_requirements` that I hadn't fully appreciated yet when writing that list. If you have suggestions how to improve that list or the table, please make a suggestion, and I'll happily link to your comment (or modify mine, if you prefer).

**Comment by h-vetinari** [comment]
I'm encountering a strange issue in https://github.com/conda-forge/pyarrow-feedstock/pull/139, where a dependency has been compiled against `c_stdlib_version 2.28`, but then the library fails to load
```
/lib64/libc.so.6: version `GLIBC_2.25' not found (required by $PREFIX/lib/python3.10/site-packages/pyarrow/../../../././libcares.so.2)
```

This happens only in the cross-compilation builds, but it happens in _all_ of them. And that despite
```
quay.io/condaforge/linux-anvil-x86_64:alma9
quay.io/condaforge/linux-anvil-x86_64-cuda11.8:ubi8
```
clearly having a new enough glibc, as confirmed by `conda info` at the beginning of the respective logs:
```
       virtual packages : __archspec=1=x86_64_v4
                          __conda=24.9.2=0
                          __cuda=11.8=0
                          __glibc=2.28=0
                          __linux=6.5.0=0
                          __unix=0=0
```
So I have no idea what's going wrong there, though it could be something related to QEMU not providing full emulation for glibc 2.28 yet? I don't actually know how that bit works....

**Comment by jakirkham** [comment]
Happy to chat if you are still seeing issues. Follow up in this thread: https://github.com/conda-forge/pyarrow-feedstock/pull/139#discussion_r1855376254

**Comment by h-vetinari** [comment]
> So I have no idea what's going wrong there, though it could be something related to QEMU not providing full emulation for glibc 2.28 yet? I don't actually know how that bit works....

Pretty sure the solution there was https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/368

**Comment by h-vetinari** [comment]
Here's another follow-up for the image switch: https://github.com/conda-forge/docker-images/pull/299
