### ISSUE TITLE
json-c 0.13.1

### ISSUE THREAD

**Issue by sodre** [conda-forge/conda-forge-pinning-feedstock#63]
Issue:
I would like to have json-c pinning updated to (include) 0.13.1.

Why:
0.13.1 is built for all three architectures, linux, osx and windows. 

Possible workarounds I can see if changing the default pin is too much at this moment.
 - Pin json-c to 0.13.1 only for Windows now. This should be fine since the library did not exist before.
 - Create a backport of the 0.13.1 windows build scripts to 0.12 feedstock and rebuild.

**Comment by dougalsutherland** [comment]
So 0.13 is totally ABI-incompatible with 0.12, but the only reason updating is bad is if there's a ton of stuff depending on it we'd need to push out builds of – ideally automated by the bot, https://github.com/regro/cf-scripts/issues/44 – and/or they broke the API compatibility so that not all software can easily compile against the new version. I don't think either is the case here, though I haven't found a json-c changelog to check.

**Comment by jakirkham** [comment]
Doesn't look like that much stuff was using it. Sadly most of that stuff had no pinning at all. So probably needs to be rebuilt with a pin anyways (and old packages pulled 😞). Switching to json-c 0.13 of some form seems reasonable. Given there doesn't appear to be 0.13.0, going to 0.13.1 sounds good.

Weird thing is the Linux and macOS 0.13.1 builds were labeled broken. Are those actually broken? If so, how?

ref: https://github.com/search?q=org%3Aconda-forge+json-c&type=Code

cc @conda-forge/json-c

**Comment by sodre** [comment]
json-c it not actually broken. It was tagged as such because it was creating conflicts with libraries that did not pin correctly, e.g. gdal. 

cf: @ocefpaf's [request](https://github.com/conda-forge/json-c-feedstock/issues/9#issuecomment-389868511) to have it removed until things were worked out.

**Comment by ocefpaf** [comment]
> json-c it not actually broken. It was tagged as such because it was creating conflicts with libraries that did not pin correctly, e.g. gdal.

Yep.

> cf: @ocefpaf's request to have it removed until things were worked out.

As soon as I can fix the gdal build we can move it forward.

**Comment by jakirkham** [comment]
Thanks for clarifying.

**Comment by jakirkham** [comment]
As these aren't really broken, have labeled them `hold` instead just so it is clearer what is going on.

**Comment by jakirkham** [comment]
FYI looks like `libgdal` was rebuilt and the `json-c` packages have been moved back to `main`.

xref: https://github.com/conda-forge/libgdal-feedstock/pull/42

**Comment by CJ-Wright** [comment]
json_c is now pinned to 0.13
