### ISSUE TITLE
Add pre-commit for .toml files

### ISSUE THREAD

**Issue by beckermr** [conda-forge/conda-forge-pinning-feedstock#6315]
I broke the linter through some misformatted toml in this repo for the linter hints. We should add a pre-commit check for this.

**Comment by jakirkham** [comment]
Referring to the linter hints in particular

https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/0a6173d40f5467fd4b67cf3d099fc03bcce9a31d/recipe/linter_hints/hints.toml#L1
