### ISSUE TITLE
Is there an easy way to install compilers in your local environment?

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/conda-forge-pinning-feedstock#650]
https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/aa141c0624f9f116ed884deb713e97d5455382ed/recipe/conda_build_config.yaml#L8

Makes it seem like I should be able to type

```
conda install gcc
```
but alas, that doesn't work.

Is there an easy way for me to install native compilers on my machine?

**Comment by jakirkham** [comment]
Have you tried the `compilers` package?

**Comment by xhochy** [comment]
Or alternatively the language-variants like `cxx-compiler`?

**Comment by hmaarrfk** [comment]
whoa, genius!

I guess this only works for conda-forge, not defaults though
https://anaconda.org/default/compilers
https://anaconda.org/conda-forge/compilers

**Comment by jakirkham** [comment]
Oh cool. Didn't realize they built these out in `defaults` too. Good to know.

We should document this somewhere. Do you have any thoughts on where it might best live?

**Comment by hmaarrfk** [comment]
No, sorry, my point is that defaults should really build these out. 

Would be really nice since we are so closely aligned.

The defaultlink doesn't worm

**Comment by jakirkham** [comment]
Oh sorry I misread. Thanks for correcting me 🙂
