### ISSUE TITLE
Bump GCC pins for CUDA 12.6

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/conda-forge-pinning-feedstock#6736]
As a follow-up to #6720 - I just realised that bumping to 12.6 means we should have updated GCC pins as well. The upstream [docs](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#host-compiler-support-policy) (found the reference in https://github.com/conda-forge/nvcc-feedstock/issues/51) say that nvcc compatible with "GCC 6.x - 13.2". We're on 13.3 though.

Is the minor-level bound really enforced? I don't remember that in previous nvcc constraints for gcc (which were major-only AFAIR).

_Originally posted by @h-vetinari in https://github.com/conda-forge/conda-forge-pinning-feedstock/issues/6720#issuecomment-2495839372_

**Comment by h-vetinari** [comment]
@carterbox commented in #6720:
> [> NVCC performs a version check on the host compiler’s major version and so newer minor versions of the compilers listed below will be supported, but major versions falling outside the range will not be supported.](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html#host-compiler-support-policy)
> 
> I would assume that the minor version specification means that this is the one they have tested.

**Comment by bdice** [comment]
I've looked at this before. I'm pretty sure that matching the minor version is not enforced, but major version support is enforced. In other words, gcc 13.3 should be fine if nvcc claims support for 13.2, but gcc 14.0 would not work.

**Comment by h-vetinari** [comment]
I tried this by overriding the pinning in a feedstock (https://github.com/h-vetinari/faiss-split-feedstock/commit/a4002e0d40b5d955139b046fa7432cf02cfebd0a). It works on CUDA 12.6, but doesn't on CUDA 12.4 for ppc, where it yields:
```
Could not solve for environment specs
The following packages are incompatible
├─ cuda-nvcc_linux-ppc64le =12.4 * is installable with the potential options
│  ├─ cuda-nvcc_linux-ppc64le 12.4.131 would require
│  │  └─ cuda-nvcc-tools =12.4.131 *, which requires
│  │     └─ gcc_impl_linux-64 >=6,<13 *, which can be installed;
│  └─ [...]
└─ gxx_linux-ppc64le =13 * is not installable because there are no viable options
```
