### ISSUE TITLE
graphviz pin 2.40

### ISSUE THREAD

**Issue by k-dominik** [conda-forge/conda-forge-pinning-feedstock#688]
graphviz is pinned to `2.40`. However, the latest windows build is `2.38.0`. Windows with graphviz as a dependency will not build on windows right now

e.g. https://github.com/conda-forge/lemon-feedstock/pull/5, with [corresponding build issue](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=184168&view=logs&j=f97ca392-d626-52d0-4b2e-4b27aa319a77&t=7b750183-140d-50ae-3ee1-cbef6218bdf6&l=62)

```
conda.exceptions.ResolvePackageNotFound: 
  - graphviz=2.40
```

https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/9898f7005d1aabb811e4aba38ece5b3003f4f160/recipe/conda_build_config.yaml#L413-L414

as far as solutions go, it's probably
 * to add a `[unix]` selector after the `2.40` one and adding `2.38` with `[win]`, or
 * to obtain a current build on windows as well...

**Comment by jakirkham** [comment]
Yep saw this as well. Thanks for raising @k-dominik! 😄

We should just add a selector as you suggest. Would you be willing to send a PR? 😉
