### ISSUE TITLE
pin vtk and occt

### ISSUE THREAD

**Issue by looooo** [conda-forge/conda-forge-pinning-feedstock#69]
I think it's better to pin vtk as much as possible:
`vtk: min_pin="x.x.x" max_pin="x.x.x"`

occt should be ok with this:
`occt: min_pin="x.x" max_pin="x.x"`

**Comment by dougalsutherland** [comment]
Yeah, `vtk` definitely needs [full pinning](https://abi-laboratory.pro/tracker/timeline/vtk/), it removes symbols in patch releases all the time.

Does anything / is anything expected to link against occt?

**Comment by looooo** [comment]
> Does anything / is anything expected to link against occt?

mainly pyocct and freecad (both not yet ready, but on the way).

**Comment by looooo** [comment]
https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/70

**Comment by jakirkham** [comment]
So does [occt]( https://abi-laboratory.pro/?view=timeline&l=opencascade ). Though they don't seem to have patch releases AFAICT.
