### ISSUE TITLE
CUDA on ppc64le / aarch64

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/conda-forge-pinning-feedstock#725]
Now that `cudatoolkit==10.2` is available on `defaults` and `linux-anvil-ppc64le-cuda` is on Docker, is it possible to add this configuration to the `cuda_compiler_version` list and corresponding zipped keys?

-- edit see summary on current status here --

**Comment by jakirkham** [comment]
Sounds fine to me. Do you want to add a PR?

Probably involves doing something like this with `nvcc` first ( https://github.com/conda-forge/nvcc-feedstock/pull/38 ) and then reverting it later ( https://github.com/conda-forge/nvcc-feedstock/pull/39 ) once `conda-forge-pinning` is updated as before ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/377 ).

I guess the other question is, do we want the older CUDA versions there as well ( https://github.com/AnacondaRecipes/cudatoolkit-feedstock/issues/8 )?

**Comment by leofang** [comment]
@jaimergp Is a PR to this feedstock the final step to get it up and running?

**Comment by jaimergp** [comment]
@leofang - I think the current support for PPC64LE is only in "manual mode", aka maintaining your own `conda_build_config.yaml`, as hinted in https://github.com/conda-forge/nvcc-feedstock/pull/66#issuecomment-831736561


However, if the teams thinks that a migration is worth for PPC-10.2, I'd be ok with it.

**Comment by jakirkham** [comment]
It might be worth migrating, but it might be better to do this once we have ARM as well

**Comment by leofang** [comment]
@jakirkham Is there anyone working on ARM now?

**Comment by jaimergp** [comment]
I have summarized the status in https://github.com/conda-forge/cudatoolkit-feedstock/issues/64, where I think it makes more sense to have this conversation. I'd rather close this one here because it took me ages to find it :D 

cc @leofang @jakirkham -- note that right now there's no way to add functioning ARM support due to the CentOS8. CUDA 10.2 for PPC is technically there and can be migrated to if we want.

**Comment by jakirkham** [comment]
Closing now that PR ( https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/2527 ) is merged
