### ISSUE TITLE
Update to boost 174 produces failing builds mixing boost versions.

### ISSUE THREAD

**Issue by darioizzo** [conda-forge/conda-forge-pinning-feedstock#775]
*Issue*: the PR opened by the bot for updating to boost 174 fails.
*Project*: https://github.com/conda-forge/pykep-feedstock/pull/14

*Analysis*: I am not sure why but it seems that a lot of strange builds are spawned mixing 172 with 174 boost packages? @isuruf suggested this may be a bug hence I opened the issue.

**Comment by xhochy** [comment]
I would have expected that adding the following to the migration would help but testing this in https://github.com/conda-forge/turbodbc-feedstock/pull/46/files locally didn't produce a change after a rerender.

```
zip_keys:
  -
    - boost_cpp
    - boost
```

**Comment by isuruf** [comment]
@xhochy, conda-smithy uses the values from `cfp` instead of the migrator. You need a local checkout of cfp and then point conda-smithy towards that
