### ISSUE TITLE
Add aarch/ppc compatible pin for jasper

### ISSUE THREAD

**Issue by Tobias-Fischer** [conda-forge/conda-forge-pinning-feedstock#891]
Jasper is pinned to `1.900.1` (see https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml#L456) but for aarch/ppc only version `1.900.31` is available (https://anaconda.org/conda-forge/jasper/files).

See Windows related PR: https://github.com/conda-forge/conda-forge-pinning-feedstock/pull/659

**Comment by CJ-Wright** [comment]
@beckermr I think this would fall nicely under your new feature!

**Comment by Tobias-Fischer** [comment]
Jasper is simply pinned to 1 now for non-win (after merging #659). So this can be closed.

**Comment by Tobias-Fischer** [comment]
This was fixed at some point
